1. Os executivos de uma empresa resolveram dar um abono aos seus colaboradores em reconhecimento ao bom resultado alcançado durante o ano que passou. Para isto contratou você para desenvolver a aplicação que servirá como uma projeção de quanto será gasto com o pagamento deste abono.
Após reuniões envolvendo a diretoria executiva, a diretoria financeira e os representantes do sindicato laboral, chegou-se a seguinte forma de cálculo:

* Cada funcionário receberá o equivalente a 20% do seu salário bruto de dezembro; 
* O piso do abono será de 100 reais, isto é, aqueles funcionários cujo salário for muito baixo, recebem este valor mínimo; 
* Neste momento, não se deve ter nenhuma preocupação com colaboradores com tempo menor de casa, descontos, impostos ou outras particularidades. 

Seu programa deverá permitir a digitação do salário de um número indefinido (desconhecido) de salários. Um valor de salário igual a 0 (zero) encerra a digitação. Após a entrada de todos os dados o programa deverá calcular o valor do abono concedido a cada colaborador, de acordo com a regra definida acima. Ao final, o programa deverá apresentar:

* O salário de cada funcionário, juntamente com o valor do abono;
* O número total de funcionário processados;
* O valor total a ser gasto com o pagamento do abono;
* O número de funcionário que receberá o valor mínimo de 100 reais;
* O maior valor pago como abono;

Por exemplo:

Projeção de Gastos com Abono
============================ 
 
Salário: 1000
Salário: 300
Salário: 500
Salário: 100
Salário: 4500
Salário: 0
 
Salário    - Abono     
R$ 1000.00 - R$  200.00
R$  300.00 - R$  100.00
R$  500.00 - R$  100.00
R$  100.00 - R$  100.00
R$ 4500.00 - R$  900.00
 
Foram processados 5 colaboradores
Total gasto com abonos: R$ 1400.00
Valor mínimo pago a 3 colaboradores
Maior valor de abono pago: R$ 900.00

In [6]:
S = []
A = []
while(1):
    s = int(input("Digite o salario do colaborador"))
    if s==0:
        break
    S.append(s)
    A.append(max([0.20*s,100]) )

print(f"Foram cadastrados {len(S)} colaboradores")
print(f"Total de gastos de abono de R${sum(A)}")
print(f"Valor minimo pago a {sum([i==100 for i in A])} colaboradores")
print(f"Maximo valor de abono pago R${max(A)}")



for i in range(len(S)):
    salario = S[i]
    abono = A[i]
    print(f"salario {salario} - abono {abono}")

Foram cadastrados 5 colaboradores
Total de gastos de abono de R$1400.0
Valor minimo pago a 3 colaboradores
Maximo valor de abono pago R$900.0
salario 1000 - abono 200.0
salario 300 - abono 100
salario 500 - abono 100.0
salario 100 - abono 100
salario 4500 - abono 900.0

2. Uma grande emissora de televisão quer fazer uma enquete entre os seus telespectadores para saber qual o melhor jogador após cada partida do campeonato. Para isto, faz-se necessário o desenvolvimento de um programa, que será utilizado pelas telefonistas, para a computação dos votos. Sua equipe foi contratada para desenvolver este programa, utilizando a linguagem de programação __Python__. Para computar cada voto, a telefonista digitará um número, entre 1 e 23, correspondente ao número da camisa do jogador. Um número de jogador igual zero, indica que a votação foi encerrada. Se um número inválido for digitado, o programa deve ignorá-lo, mostrando uma breve mensagem de aviso, e voltando a pedir outro número. Após o final da votação, o programa deverá exibir:

* O total de votos computados;
* Os números e respectivos votos de todos os jogadores que receberam votos;
* O percentual de votos de cada um destes jogadores;
* O número do jogador escolhido como o melhor jogador da partida, juntamente com o número de votos e o percentual de votos dados a ele.

Observe que os votos inválidos e o zero final não devem ser computados como votos. O resultado aparece ordenado pelo número do jogador. 

Por exemplo:

Enquete: Quem foi o melhor jogador?

Número do jogador (0=fim): 9
Número do jogador (0=fim): 10
Número do jogador (0=fim): 9
Número do jogador (0=fim): 10
Número do jogador (0=fim): 11
Número do jogador (0=fim): 10
Número do jogador (0=fim): 50
Informe um valor entre 1 e 23 ou 0 para sair!
Número do jogador (0=fim): 9
Número do jogador (0=fim): 9
Número do jogador (0=fim): 0

Resultado da votação:

Foram computados 8 votos.

Jogador Votos           %
9               4               50,0%
10              3               37,5%
11              1               12,5%
O melhor jogador foi o número 9, com 4 votos, correspondendo a 50% do total de votos.

In [10]:
votos = [0 for _ in range(22)]

print()
while(1):
    v = int(input("Digite o numero entre 1 e 23"))
    if v==0:
        print("fim\n\n")
        break

    if v<0 or v>23:
        print("valor invalido")
    else:
        votos[v-1]+=1
    

qVotos = sum(votos)
print(f"Foram computados {qVotos} votos\n\n")


maxVotos = max(votos)

melhorJogador = []

for i,voto in enumerate(votos):
    if voto!=0:
        print(f"Camisa: {i+1}, Votos: {voto}, Porcentagem: {voto/qVotos*100}%")
    if voto==maxVotos:
        melhorJogador.append(i)


print("\nO(s) melhor(es) jogador(es) são:\n")
for mj in melhorJogador:
     print(f"Camisa: {mj+1}, Votos: {votos[mj]}, Porcentagem: {maxVotos/qVotos*100}%")

fim


Foram computados 34 votos


Camisa: 1, Votos: 9, Porcentagem: 26.47058823529412%
Camisa: 2, Votos: 4, Porcentagem: 11.76470588235294%
Camisa: 3, Votos: 2, Porcentagem: 5.88235294117647%
Camisa: 4, Votos: 5, Porcentagem: 14.705882352941178%
Camisa: 5, Votos: 3, Porcentagem: 8.823529411764707%
Camisa: 6, Votos: 2, Porcentagem: 5.88235294117647%
Camisa: 7, Votos: 1, Porcentagem: 2.941176470588235%
Camisa: 8, Votos: 1, Porcentagem: 2.941176470588235%
Camisa: 9, Votos: 1, Porcentagem: 2.941176470588235%
Camisa: 10, Votos: 3, Porcentagem: 8.823529411764707%
Camisa: 11, Votos: 1, Porcentagem: 2.941176470588235%
Camisa: 12, Votos: 1, Porcentagem: 2.941176470588235%
Camisa: 22, Votos: 1, Porcentagem: 2.941176470588235%
O(s) melhor(es) jogador(es) são:
Camisa: 1, Votos: 9, Porcentagem: 26.47058823529412%

3. Carregue para um DataFrame a lista de municípios de fronteira do Brasil utilizando o arquivo "datasets/arq_municipios_fronteiricos.csv".

4. Realize um tratamento na coluna Município para remover os números e hifens.

* primeiro crie uma função recebe uma string com o nome do município, realiza a remoção dos números e hifens e retorna a nova string tratada
* faça os testes com a sua função até que o resultado esteja satisfatório
* passe a sua função como parâmetro para o método apply do DataFrame

5. Ainda utilizando o DataFrame carregado no exercício anterior, verifique os tipos de dados das colunas do dataframe. Todos os dados numéricos deverão ser transformados para tipos numéricos.

* utilize o método info() do DataFrame para saber detalhes dos tipos de dados das colunas

6. Crie uma coluna com a sigla dos estados.

* crie um set à partir da coluna Estados. Atribua a uma variável chamada nomes_estados.
* crie um dicionário onde o nome completo do estado é a chave e a sigla é o valor.
* utilize a função map do DataFrame para criar uma nova coluna de siglas à partir dos nomes dos estados. Passe o dicionário criado para a função map. Atribua a Série criada à variável coluna_siglas_uf.

In [59]:
import pandas as pd

csv = pd.read_csv("./arq_municipios_fronteiricos.csv",decimal=",",thousands=".")
csv.head()

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005,PIB per capita (R$),IDH/2000
0,1 – Aceguá,Rio Grande do Sul,1550,4138,2.66,71.638.000,17.266,ni
1,2 – Acrelândia,Acre,1575,11520,7.31,114.350.000,9.986,"0,680"
2,3 – Alecrim,Rio Grande do Sul,315,7357,23.35,44.373.000,5.944,"0,743"
3,4 – Almeirim,Pará,72960,30903,0.42,462.258.000,13.485,"0,745"
4,5 – Alta Floresta d'Oeste,Rondônia,7067,23857,3.37,186.812.000,6.525,"0,715"

In [137]:
def retiraNumHifem(nomeMunicipio):
    nm = nomeMunicipio.split()
    return (" ").join(nm[2:])

In [138]:
retiraNumHifem("1 – Aceguá")

'Aceguá'

In [57]:
csv["Município"] = csv["Município"].apply(retiraNumHifem)
csv.head()

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005,PIB per capita (R$),IDH/2000
0,Aceguá,Rio Grande do Sul,1550,4138,2.66,71.638.000,17.266,ni
1,Acrelândia,Acre,1575,11520,7.31,114.350.000,9.986,"0,680"
2,Alecrim,Rio Grande do Sul,315,7357,23.35,44.373.000,5.944,"0,743"
3,Almeirim,Pará,72960,30903,0.42,462.258.000,13.485,"0,745"
4,Alta Floresta d'Oeste,Rondônia,7067,23857,3.37,186.812.000,6.525,"0,715"

In [38]:
csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Município                        122 non-null    object
 1   Estado                           122 non-null    object
 2   Área territorial                 122 non-null    int64
 3   População (IBGE/2007)            122 non-null    int64
 4   Densidade demográfica (hab/km2)  122 non-null    float64
 5   PIB (IBGE/2005                   122 non-null    object
 6   PIB per capita (R$)              122 non-null    object
 7   IDH/2000                         122 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 7.8+ KB

In [139]:

def retornaNumerico(s):
    try:
        return float(str(s).replace(".","").replace(" ","").replace(",","."))
    except:
        return None

csv = pd.read_csv("./arq_municipios_fronteiricos.csv",decimal=",",thousands=".")




csv["Município"] = csv["Município"].apply(retiraNumHifem)

csv["PIB (IBGE/2005"] = csv["PIB (IBGE/2005"].apply(retornaNumerico)

csv["PIB per capita (R$)"] = csv["PIB per capita (R$)"].apply(retornaNumerico)

csv["IDH/2000"] = csv["IDH/2000"].apply(retornaNumerico)


csv.head()


#csv.info()

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005,PIB per capita (R$),IDH/2000
0,Aceguá,Rio Grande do Sul,1550,4138,2.66,71638000.0,17266.0,NaN
1,Acrelândia,Acre,1575,11520,7.31,114350000.0,9986.0,0.680
2,Alecrim,Rio Grande do Sul,315,7357,23.35,44373000.0,5944.0,0.743
3,Almeirim,Pará,72960,30903,0.42,462258000.0,13485.0,0.745
4,Alta Floresta d'Oeste,Rondônia,7067,23857,3.37,186812000.0,6525.0,0.715

In [63]:
csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Município                        122 non-null    object
 1   Estado                           122 non-null    object
 2   Área territorial                 122 non-null    int64
 3   População (IBGE/2007)            122 non-null    int64
 4   Densidade demográfica (hab/km2)  122 non-null    float64
 5   PIB (IBGE/2005                   122 non-null    float64
 6   PIB per capita (R$)              122 non-null    float64
 7   IDH/2000                         104 non-null    float64
dtypes: float64(4), int64(2), object(2)
memory usage: 7.8+ KB

In [140]:
nomes_estados = csv["Estado"]


dicEstados = {
    'Acre': 'AC',
    'Alagoas': 'AL',
    'Amapá': 'AP',
    'Amazonas': 'AM',
    'Bahia': 'BA',
    'Ceará': 'CE',
    'Distrito Federal': 'DF',
    'Espírito Santo': 'ES',
    'Goiás': 'GO',
    'Maranhão': 'MA',
    'Mato Grosso': 'MT',
    'Mato Grosso do Sul': 'MS',
    'Minas Gerais': 'MG',
    'Pará': 'PA',
    'Paraíba': 'PB',
    'Paraná': 'PR',
    'Pernambuco': 'PE',
    'Piauí': 'PI',
    'Rio de Janeiro': 'RJ',
    'Rio Grande do Norte': 'RN',
    'Rio Grande do Sul': 'RS',
    'Rondônia': 'RO',
    'Roraima': 'RR',
    'Santa Catarina': 'SC',
    'Santa Cataria': 'SC',
    'São Paulo': 'SP',
    'Sergipe': 'SE',
    'Tocantins': 'TO'
}

siglas_uf = nomes_estados.map(dicEstados)

csv["Siglas"] = siglas_uf
csv

,Município,Estado,Área territorial,População (IBGE/2007),Densidade demográfica (hab/km2),PIB (IBGE/2005,PIB per capita (R$),IDH/2000,Siglas
0,Aceguá,Rio Grande do Sul,1550,4138,2.66,7.163800e+07,17266.0,NaN,RS
1,Acrelândia,Acre,1575,11520,7.31,1.143500e+08,9986.0,0.680,AC
2,Alecrim,Rio Grande do Sul,315,7357,23.35,4.437300e+07,5944.0,0.743,RS
3,Almeirim,Pará,72960,30903,0.42,4.622580e+08,13485.0,0.745,PA
4,Alta Floresta d'Oeste,Rondônia,7067,23857,3.37,1.868120e+08,6525.0,0.715,RO
...,...,...,...,...,...,...,...,...,...
117,Tunápolis,Santa Cataria,133,4650,34.96,4.084500e+07,9420.0,0.821,SC
118,Uiramutã,Roraima,8066,7403,0.91,2.725100e+07,4238.0,0.542,RR
119,Uruguaiana,Rio Grande do Sul,5716,123743,21.64,1.187038e+09,8798.0,0.788,RS
120,Vila Bela da Santíssima Trindade,Mato Grosso,13631,13886,1.01,1.169080e+08,8047.0,0.715,MT
121,Xapuri,Acre,5251,14314,2.72,8.237700e+07,6016.0,0.669,AC

In [141]:
csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 9 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Município                        122 non-null    object
 1   Estado                           122 non-null    object
 2   Área territorial                 122 non-null    int64
 3   População (IBGE/2007)            122 non-null    int64
 4   Densidade demográfica (hab/km2)  122 non-null    float64
 5   PIB (IBGE/2005                   122 non-null    float64
 6   PIB per capita (R$)              122 non-null    float64
 7   IDH/2000                         104 non-null    float64
 8   Siglas                           122 non-null    object
dtypes: float64(4), int64(2), object(3)
memory usage: 8.7+ KB