In [206]:
import pandas as pd

df2003 = pd.read_csv("INMET_CO_DF_A001_BRASILIA_01-01-2003_A_31-12-2003.CSV", encoding='iso-8859-1', decimal=',', delimiter=';', skiprows=8)
df2013 = pd.read_csv("INMET_CO_DF_A001_BRASILIA_01-01-2013_A_31-12-2013.CSV", encoding='iso-8859-1', decimal=',', delimiter=';', skiprows=8)
df2023 = pd.read_csv("INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023.CSV", encoding='iso-8859-1', decimal=',', delimiter=';', skiprows=8)

In [207]:
df2003.drop(["Unnamed: 19"], axis=1, inplace=True)
df2013 .drop(["Unnamed: 19"], axis=1, inplace=True)
df2023.drop(["Unnamed: 19"], axis=1, inplace=True)

df2023.rename(columns={'Data':'DATA (YYYY-MM-DD)', 'Hora UTC':'HORA (UTC)', 'RADIACAO GLOBAL (Kj/m²)': 'RADIACAO GLOBAL (KJ/m²)'}, inplace=True)

In [208]:
df2003.head()

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2003-01-01,00:00,0.0,886.9,887.0,886.5,-9999,20.3,18.8,20.4,20.2,18.9,18.7,91,90,91,308,2.1,1.4
1,2003-01-01,01:00,0.0,887.3,887.3,886.9,-9999,19.9,18.5,20.3,19.9,18.8,18.5,92,91,92,302,2.2,1.3
2,2003-01-01,02:00,0.0,887.8,887.8,887.3,-9999,19.8,18.5,20.1,19.8,18.8,18.4,92,92,92,302,2.7,1.6
3,2003-01-01,03:00,0.0,886.9,887.8,886.9,-9999,19.5,18.5,19.8,19.5,18.6,18.4,94,92,94,295,3.4,2.0
4,2003-01-01,04:00,0.0,886.8,886.9,886.7,-9999,19.2,18.0,19.5,19.2,18.5,18.0,94,93,93,313,3.9,2.5

In [209]:
df2013.head()

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2013-01-01,00:00,0.0,885.7,885.7,885.1,-9999.0,24.1,14.2,25.0,24.1,14.4,13.9,54,50,54,112,4.6,2.3
1,2013-01-01,01:00,0.0,886.5,886.5,885.7,-9999.0,23.5,14.5,24.2,23.4,14.6,14.2,58,54,57,110,5.0,2.7
2,2013-01-01,02:00,0.0,886.9,886.9,886.5,-9999.0,23.3,14.5,23.5,23.2,14.7,14.4,59,56,58,91,5.4,3.4
3,2013-01-01,03:00,0.0,886.5,886.9,886.5,-9999.0,22.8,14.6,23.3,22.8,14.7,14.4,60,57,60,81,5.4,3.1
4,2013-01-01,04:00,0.0,886.0,886.5,886.0,-9999.0,22.4,14.5,22.9,22.2,14.6,14.3,62,59,61,86,5.3,2.9

In [210]:
df2023.head()

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2023/01/01,0000 UTC,0.0,887.7,887.7,887.2,NaN,20.1,17.9,20.9,20.0,19.2,17.8,91.0,87.0,87.0,187.0,3.3,1.2
1,2023/01/01,0100 UTC,0.0,888.1,888.1,887.7,NaN,19.2,17.5,20.1,19.2,17.8,17.4,90.0,87.0,90.0,153.0,2.9,0.8
2,2023/01/01,0200 UTC,0.0,887.8,888.1,887.8,NaN,19.3,17.6,19.5,19.0,17.8,17.3,90.0,89.0,90.0,145.0,2.5,1.5
3,2023/01/01,0300 UTC,0.0,887.8,887.9,887.7,NaN,19.3,17.7,19.4,19.1,17.8,17.5,91.0,90.0,91.0,162.0,3.2,1.4
4,2023/01/01,0400 UTC,0.0,887.6,887.9,887.6,NaN,19.7,18.1,19.7,19.1,18.1,17.4,91.0,90.0,90.0,140.0,5.7,2.7

In [211]:
df = pd.concat([df2003,df2013,df2023])
df.head()

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)"
0,2003-01-01,00:00,0.0,886.9,887.0,886.5,-9999.0,20.3,18.8,20.4,20.2,18.9,18.7,91.0,90.0,91.0,308.0,2.1,1.4
1,2003-01-01,01:00,0.0,887.3,887.3,886.9,-9999.0,19.9,18.5,20.3,19.9,18.8,18.5,92.0,91.0,92.0,302.0,2.2,1.3
2,2003-01-01,02:00,0.0,887.8,887.8,887.3,-9999.0,19.8,18.5,20.1,19.8,18.8,18.4,92.0,92.0,92.0,302.0,2.7,1.6
3,2003-01-01,03:00,0.0,886.9,887.8,886.9,-9999.0,19.5,18.5,19.8,19.5,18.6,18.4,94.0,92.0,94.0,295.0,3.4,2.0
4,2003-01-01,04:00,0.0,886.8,886.9,886.7,-9999.0,19.2,18.0,19.5,19.2,18.5,18.0,94.0,93.0,93.0,313.0,3.9,2.5

In [212]:
def separaDMY(data):
    lista = str(data).replace("-","/").split("/")
    ano, mes, dia =  [int(i) for i in lista]
    return (ano,mes,dia)

In [213]:

multiIndex = pd.MultiIndex.from_tuples(df["DATA (YYYY-MM-DD)"].apply(separaDMY), names=["ANO","MES","DIA"])
df.set_index(multiIndex, inplace=True)
df

             DATA (YYYY-MM-DD) HORA (UTC)  PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \
ANO  MES DIA
2003 1   1          2003-01-01      00:00                               0.0
         1          2003-01-01      01:00                               0.0
         1          2003-01-01      02:00                               0.0
         1          2003-01-01      03:00                               0.0
         1          2003-01-01      04:00                               0.0
...                        ...        ...                               ...
2023 12  31         2023/12/31   1900 UTC                               0.0
         31         2023/12/31   2000 UTC                               0.0
         31         2023/12/31   2100 UTC                               0.0
         31         2023/12/31   2200 UTC                               0.0
         31         2023/12/31   2300 UTC                               0.0

              PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  \
ANO  MES DIA
2003 1   1                                                886.9
         1                                                887.3
         1                                                887.8
         1                                                886.9
         1                                                886.8
...                                                         ...
2023 12  31                                               884.2
         31                                               883.7
         31                                               883.5
         31                                               884.5
         31                                               885.3

              PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)  \
ANO  MES DIA
2003 1   1                                              887.0
         1                                              887.3
         1                                              887.8
         1                                              887.8
         1                                              886.9
...                                                       ...
2023 12  31                                             885.2
         31                                             884.3
         31                                             883.7
         31                                             884.5
         31                                             885.3

              PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)  \
ANO  MES DIA
2003 1   1                                               886.5
         1                                               886.9
         1                                               887.3
         1                                               886.9
         1                                               886.7
...                                                        ...
2023 12  31                                              884.2
         31                                              883.7
         31                                              883.4
         31                                              883.5
         31                                              884.5

              RADIACAO GLOBAL (KJ/m²)  \
ANO  MES DIA
2003 1   1                    -9999.0
         1                    -9999.0
         1                    -9999.0
         1                    -9999.0
         1                    -9999.0
...                               ...
2023 12  31                    1252.2
         31                    1178.8
         31                     873.0
         31                     104.0
         31                       NaN

              TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)  \
ANO  MES DIA
2003 1   1                                            20.3
         1                                            19.9
         1                                            19.8
         1                                            19.5
         1                                            19.2
...                                                    ...
2023 12  31                                           26.1
         31                                           27.7
         31                                           25.5
         31                                           23.4
         31                                           22.6

              TEMPERATURA DO PONTO DE ORVALHO (°C)  \
ANO  MES DIA
2003 1   1                                    18.8
         1                                    18.5
         1                                    18.5
         1                                    18.5
         1                                    18.0
...                                            ...
2023 12  31                                   18.4
         31                                   18.1
         31                                   17.4
         31                                   18.2
         31                                   18.6

              TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)  \
ANO  MES DIA
2003 1   1                                          20.4
         1                                          20.3
         1                                          20.1
         1                                          19.8
         1                                          19.5
...                                                  ...
2023 12  31                                         28.1
         31                                         27.7
         31                                         27.7
         31                                         25.5
         31                                         23.4

              TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)  \
ANO  MES DIA
2003 1   1                                          20.2
         1                                          19.9
         1                                          19.8
         1                                          19.5
         1                                          19.2
...                                                  ...
2023 12  31                                         26.0
         31                                         25.8
         31                                         25.5
         31                                         23.4
         31                                         22.3

              TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)  \
ANO  MES DIA
2003 1   1                                                18.9
         1                                                18.8
         1                                                18.8
         1                                                18.6
         1                                                18.5
...                                                        ...
2023 12  31                                               19.0
         31                                               18.2
         31                                               18.0
         31                                               18.2
         31                                               18.6

              TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)  \
ANO  MES DIA
2003 1   1                                                18.7
         1                                                18.5
         1                                                18.4
         1                                                18.4
         1                                                18.0
...                                                        ...
2023 12  31                                               16.9
         31                                               16.9
         31                                               16.9
         31                                               17.4
         31                                               18.3

              UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)  \
ANO  MES DIA
2003 1   1                                        91.0
         1                                        92.0
         1                                        92.0
         1                                        94.0
         1                                        94.0
...                                                ...
2023 12  31                                       64.0
         31                                       62.0
         31                                       62.0
         31                                       72.0
         31                                       79.0

              UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)  \
ANO  MES DIA
2003 1   1                                        90.0
         1                                        91.0
         1                                        92.0
         1                                        92.0
         1                                        93.0
...                                                ...
2023 12  31                                       52.0
         31                                       53.0
         31                                       52.0
         31                                       61.0
         31                                       73.0

              UMIDADE RELATIVA DO AR, HORARIA (%)  \
ANO  MES DIA
2003 1   1                                   91.0
         1                                   92.0
         1                                   92.0
         1                                   94.0
         1                                   93.0
...                                           ...
2023 12  31                                  63.0
         31                                  56.0
         31                                  61.0
         31                                  72.0
         31                                  78.0

              VENTO, DIREÇÃO HORARIA (gr) (° (gr))  \
ANO  MES DIA
2003 1   1                                   308.0
         1                                   302.0
         1                                   302.0
         1                                   295.0
         1                                   313.0
...                                            ...
2023 12  31                                    1.0
         31                                  314.0
         31                                  300.0
         31                                  293.0
         31                                  285.0

              VENTO, RAJADA MAXIMA (m/s)  VENTO, VELOCIDADE HORARIA (m/s)
ANO  MES DIA
2003 1   1                           2.1                              1.4
         1                           2.2                              1.3
         1                           2.7                              1.6
         1                           3.4                              2.0
         1                           3.9                              2.5
...                                  ...                              ...
2023 12  31                          5.3                              2.1
         31                          5.2                              1.9
         31                          5.1                              2.7
         31                          4.8                              2.0
         31                          3.7                              1.4

[26280 rows x 19 columns]

In [214]:
mi = []
for columns in df.columns:
    a = (columns,"")
    if(columns.find("PRESSAO")>-1 or columns.find("PRESSÃO")>-1):
        a = ("PRESSÃO",columns)
    if(columns.find("TEMPERATURA")>-1):
        a = ("TEMPERATURA",columns)
    if(columns.find("UMIDADE")>-1):
        a = ("UMIDADE",columns)
    if(columns.find("VENTO")>-1):
        a = ("VELOCIDADE DO VENTO",columns)
    mi.append(a)
mi

[('DATA (YYYY-MM-DD)', ''),
 ('HORA (UTC)', ''),
 ('PRECIPITAÇÃO TOTAL, HORÁRIO (mm)', ''),
 ('PRESSÃO', 'PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)'),
 ('PRESSÃO', 'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)'),
 ('PRESSÃO', 'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)'),
 ('RADIACAO GLOBAL (KJ/m²)', ''),
 ('TEMPERATURA', 'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)'),
 ('TEMPERATURA', 'TEMPERATURA DO PONTO DE ORVALHO (°C)'),
 ('TEMPERATURA', 'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)'),
 ('TEMPERATURA', 'TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)'),
 ('TEMPERATURA', 'TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)'),
 ('TEMPERATURA', 'TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)'),
 ('UMIDADE', 'UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)'),
 ('UMIDADE', 'UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)'),
 ('UMIDADE', 'UMIDADE RELATIVA DO AR, HORARIA (%)'),
 ('VELOCIDADE DO VENTO', 'VENTO, DIREÇÃO HORARIA (gr) (° (gr))'),
 ('VELOCIDADE DO VENTO', 'VENTO, RAJADA MAXIMA (m/s)'),
 ('VELOCIDADE DO VENTO', 'VENTO, VELOCIDADE HORARIA (m/s)')]

In [215]:
df.columns = pd.MultiIndex.from_tuples(mi)
df

             DATA (YYYY-MM-DD) HORA (UTC) PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \

ANO  MES DIA
2003 1   1          2003-01-01      00:00                              0.0
         1          2003-01-01      01:00                              0.0
         1          2003-01-01      02:00                              0.0
         1          2003-01-01      03:00                              0.0
         1          2003-01-01      04:00                              0.0
...                        ...        ...                              ...
2023 12  31         2023/12/31   1900 UTC                              0.0
         31         2023/12/31   2000 UTC                              0.0
         31         2023/12/31   2100 UTC                              0.0
         31         2023/12/31   2200 UTC                              0.0
         31         2023/12/31   2300 UTC                              0.0

                                                           PRESSÃO  \
             PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
ANO  MES DIA
2003 1   1                                                886.9
         1                                                887.3
         1                                                887.8
         1                                                886.9
         1                                                886.8
...                                                         ...
2023 12  31                                               884.2
         31                                               883.7
         31                                               883.5
         31                                               884.5
         31                                               885.3

                                                              \
             PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
ANO  MES DIA
2003 1   1                                             887.0
         1                                             887.3
         1                                             887.8
         1                                             887.8
         1                                             886.9
...                                                      ...
2023 12  31                                            885.2
         31                                            884.3
         31                                            883.7
         31                                            884.5
         31                                            885.3

                                                               \
             PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
ANO  MES DIA
2003 1   1                                              886.5
         1                                              886.9
         1                                              887.3
         1                                              886.9
         1                                              886.7
...                                                       ...
2023 12  31                                             884.2
         31                                             883.7
         31                                             883.4
         31                                             883.5
         31                                             884.5

             RADIACAO GLOBAL (KJ/m²)  \

ANO  MES DIA
2003 1   1                   -9999.0
         1                   -9999.0
         1                   -9999.0
         1                   -9999.0
         1                   -9999.0
...                              ...
2023 12  31                   1252.2
         31                   1178.8
         31                    873.0
         31                    104.0
         31                      NaN

                                              TEMPERATURA  \
             TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
ANO  MES DIA
2003 1   1                                           20.3
         1                                           19.9
         1                                           19.8
         1                                           19.5
         1                                           19.2
...                                                   ...
2023 12  31                                          26.1
         31                                          27.7
         31                                          25.5
         31                                          23.4
         31                                          22.6

                                                   \
             TEMPERATURA DO PONTO DE ORVALHO (°C)
ANO  MES DIA
2003 1   1                                   18.8
         1                                   18.5
         1                                   18.5
         1                                   18.5
         1                                   18.0
...                                           ...
2023 12  31                                  18.4
         31                                  18.1
         31                                  17.4
         31                                  18.2
         31                                  18.6

                                                         \
             TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
ANO  MES DIA
2003 1   1                                         20.4
         1                                         20.3
         1                                         20.1
         1                                         19.8
         1                                         19.5
...                                                 ...
2023 12  31                                        28.1
         31                                        27.7
         31                                        27.7
         31                                        25.5
         31                                        23.4

                                                         \
             TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
ANO  MES DIA
2003 1   1                                         20.2
         1                                         19.9
         1                                         19.8
         1                                         19.5
         1                                         19.2
...                                                 ...
2023 12  31                                        26.0
         31                                        25.8
         31                                        25.5
         31                                        23.4
         31                                        22.3

                                                               \
             TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
ANO  MES DIA
2003 1   1                                               18.9
         1                                               18.8
         1                                               18.8
         1                                               18.6
         1                                               18.5
...                                                       ...
2023 12  31                                              19.0
         31                                              18.2
         31                                              18.0
         31                                              18.2
         31                                              18.6

                                                               \
             TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
ANO  MES DIA
2003 1   1                                               18.7
         1                                               18.5
         1                                               18.4
         1                                               18.4
         1                                               18.0
...                                                       ...
2023 12  31                                              16.9
         31                                              16.9
         31                                              16.9
         31                                              17.4
         31                                              18.3

                                              UMIDADE  \
             UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
ANO  MES DIA
2003 1   1                                       91.0
         1                                       92.0
         1                                       92.0
         1                                       94.0
         1                                       94.0
...                                               ...
2023 12  31                                      64.0
         31                                      62.0
         31                                      62.0
         31                                      72.0
         31                                      79.0

                                                       \
             UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
ANO  MES DIA
2003 1   1                                       90.0
         1                                       91.0
         1                                       92.0
         1                                       92.0
         1                                       93.0
...                                               ...
2023 12  31                                      52.0
         31                                      53.0
         31                                      52.0
         31                                      61.0
         31                                      73.0

                                                  \
             UMIDADE RELATIVA DO AR, HORARIA (%)
ANO  MES DIA
2003 1   1                                  91.0
         1                                  92.0
         1                                  92.0
         1                                  94.0
         1                                  93.0
...                                          ...
2023 12  31                                 63.0
         31                                 56.0
         31                                 61.0
         31                                 72.0
         31                                 78.0

                              VELOCIDADE DO VENTO                             \
             VENTO, DIREÇÃO HORARIA (gr) (° (gr)) VENTO, RAJADA MAXIMA (m/s)
ANO  MES DIA
2003 1   1                                  308.0                        2.1
         1                                  302.0                        2.2
         1                                  302.0                        2.7
         1                                  295.0                        3.4
         1                                  313.0                        3.9
...                                           ...                        ...
2023 12  31                                   1.0                        5.3
         31                                 314.0                        5.2
         31                                 300.0                        5.1
         31                                 293.0                        4.8
         31                                 285.0                        3.7


             VENTO, VELOCIDADE HORARIA (m/s)
ANO  MES DIA
2003 1   1                               1.4
         1                               1.3
         1                               1.6
         1                               2.0
         1                               2.5
...                                      ...
2023 12  31                              2.1
         31                              1.9
         31                              2.7
         31                              2.0
         31                              1.4

[26280 rows x 19 columns]

In [216]:
df.groupby("ANO")["TEMPERATURA"].agg(["min","max","mean"])

                                      TEMPERATURA                    \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
                                              min   max        mean
ANO
2003                                      -9999.0  33.0 -570.075000
2013                                      -9999.0  32.6   -1.617511
2023                                          9.6  34.4   21.955477

                                                             \
     TEMPERATURA DO PONTO DE ORVALHO (°C)
                                      min   max        mean
ANO
2003                              -9999.0  20.1 -577.182169
2013                              -9999.0  20.5   -8.624635
2023                                 -1.1  21.5   14.184500

                                                                   \
     TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
                                            min   max        mean
ANO
2003                                    -9999.0  33.2 -609.560856
2013                                    -9999.0  32.7   -0.921632
2023                                       10.7  34.6   22.735544

                                                                   \
     TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
                                            min   max        mean
ANO
2003                                    -9999.0  32.4 -610.650297
2013                                    -9999.0  31.5   -2.265799
2023                                        9.4  33.0   21.207454

                                                                         \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
                                                  min   max        mean
ANO
2003                                          -9999.0  20.8 -616.726153
2013                                          -9999.0  21.3   -8.039772
2023                                              0.0  22.3   14.816086


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
                                                  min   max        mean
ANO
2003                                          -9999.0  19.6 -617.654007
2013                                          -9999.0  19.9   -9.173721
2023                                             -1.4  21.3   13.605751

In [217]:
df.groupby("ANO")["PRECIPITAÇÃO TOTAL, HORÁRIO (mm)"].agg(["min","max","mean"])

         min   max        mean
ANO
2003 -9999.0  33.4 -590.010502
2013 -9999.0  40.2  -23.788082
2023     0.0  23.4    0.113764

In [218]:
df.xs(1, level="MES").groupby("ANO")["TEMPERATURA"].agg(["min","max","mean"])

                                      TEMPERATURA                    \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
                                              min   max        mean
ANO
2003                                      -9999.0  29.1 -341.878226
2013                                         15.6  29.9   21.148522
2023                                         15.8  28.2   21.033602

                                                             \
     TEMPERATURA DO PONTO DE ORVALHO (°C)
                                      min   max        mean
ANO
2003                              -9999.0  20.1 -345.802823
2013                                  8.5  20.5   17.193952
2023                                 11.9  19.6   16.839113

                                                                   \
     TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
                                            min   max        mean
ANO
2003                                    -9999.0  30.0 -381.752151
2013                                       15.9  30.6   21.710349
2023                                       16.1  28.9   21.704167

                                                                   \
     TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
                                            min   max        mean
ANO
2003                                    -9999.0  28.8 -382.804032
2013                                       15.6  29.2   20.635887
2023                                       15.6  27.2   20.410618

                                                                         \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
                                                  min   max        mean
ANO
2003                                          -9999.0  20.8 -385.720968
2013                                             10.0  20.8   17.728226
2023                                             13.3  20.1   17.418414


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
                                                  min   max        mean
ANO
2003                                          -9999.0  19.6 -386.655376
2013                                              5.8  19.8   16.666398
2023                                             11.2  18.7   16.297849

In [219]:
df.xs(1, level="MES").groupby("ANO")["PRECIPITAÇÃO TOTAL, HORÁRIO (mm)"].agg(["min","max","mean"])

         min   max        mean
ANO
2003 -9999.0  14.2 -362.601344
2013     0.0  40.2    0.608602
2023     0.0  17.6    0.256452

In [220]:
def mesParaEstacao(mes):
    if mes <= 3:
        return "VERÃO"
    if mes <=6:
        return "OUTONO"
    if mes<=9:
        return "INVERNO"
    return "PRIMAVERA"

In [221]:
estacao = [mesParaEstacao(data[1]) for data in df.index]
df["ESTAÇÃO"] = estacao
df = df.set_index('ESTAÇÃO', append=True)

In [222]:
df

                       DATA (YYYY-MM-DD) HORA (UTC)  \

ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO            2003-01-01      00:00
             VERÃO            2003-01-01      01:00
             VERÃO            2003-01-01      02:00
             VERÃO            2003-01-01      03:00
             VERÃO            2003-01-01      04:00
...                                  ...        ...
2023 12  31  PRIMAVERA        2023/12/31   1900 UTC
             PRIMAVERA        2023/12/31   2000 UTC
             PRIMAVERA        2023/12/31   2100 UTC
             PRIMAVERA        2023/12/31   2200 UTC
             PRIMAVERA        2023/12/31   2300 UTC

                       PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \

ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                  0.0
             VERÃO                                  0.0
             VERÃO                                  0.0
             VERÃO                                  0.0
             VERÃO                                  0.0
...                                                 ...
2023 12  31  PRIMAVERA                              0.0
             PRIMAVERA                              0.0
             PRIMAVERA                              0.0
             PRIMAVERA                              0.0
             PRIMAVERA                              0.0

                                                                     PRESSÃO  \
                       PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                                  886.9
             VERÃO                                                  887.3
             VERÃO                                                  887.8
             VERÃO                                                  886.9
             VERÃO                                                  886.8
...                                                                   ...
2023 12  31  PRIMAVERA                                              884.2
             PRIMAVERA                                              883.7
             PRIMAVERA                                              883.5
             PRIMAVERA                                              884.5
             PRIMAVERA                                              885.3

                                                                        \
                       PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                               887.0
             VERÃO                                               887.3
             VERÃO                                               887.8
             VERÃO                                               887.8
             VERÃO                                               886.9
...                                                                ...
2023 12  31  PRIMAVERA                                           885.2
             PRIMAVERA                                           884.3
             PRIMAVERA                                           883.7
             PRIMAVERA                                           884.5
             PRIMAVERA                                           885.3

                                                                         \
                       PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                                886.5
             VERÃO                                                886.9
             VERÃO                                                887.3
             VERÃO                                                886.9
             VERÃO                                                886.7
...                                                                 ...
2023 12  31  PRIMAVERA                                            884.2
             PRIMAVERA                                            883.7
             PRIMAVERA                                            883.4
             PRIMAVERA                                            883.5
             PRIMAVERA                                            884.5

                       RADIACAO GLOBAL (KJ/m²)  \

ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                     -9999.0
             VERÃO                     -9999.0
             VERÃO                     -9999.0
             VERÃO                     -9999.0
             VERÃO                     -9999.0
...                                        ...
2023 12  31  PRIMAVERA                  1252.2
             PRIMAVERA                  1178.8
             PRIMAVERA                   873.0
             PRIMAVERA                   104.0
             PRIMAVERA                     NaN

                                                        TEMPERATURA  \
                       TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                             20.3
             VERÃO                                             19.9
             VERÃO                                             19.8
             VERÃO                                             19.5
             VERÃO                                             19.2
...                                                             ...
2023 12  31  PRIMAVERA                                         26.1
             PRIMAVERA                                         27.7
             PRIMAVERA                                         25.5
             PRIMAVERA                                         23.4
             PRIMAVERA                                         22.6

                                                             \
                       TEMPERATURA DO PONTO DE ORVALHO (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                     18.8
             VERÃO                                     18.5
             VERÃO                                     18.5
             VERÃO                                     18.5
             VERÃO                                     18.0
...                                                     ...
2023 12  31  PRIMAVERA                                 18.4
             PRIMAVERA                                 18.1
             PRIMAVERA                                 17.4
             PRIMAVERA                                 18.2
             PRIMAVERA                                 18.6

                                                                   \
                       TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                           20.4
             VERÃO                                           20.3
             VERÃO                                           20.1
             VERÃO                                           19.8
             VERÃO                                           19.5
...                                                           ...
2023 12  31  PRIMAVERA                                       28.1
             PRIMAVERA                                       27.7
             PRIMAVERA                                       27.7
             PRIMAVERA                                       25.5
             PRIMAVERA                                       23.4

                                                                   \
                       TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                           20.2
             VERÃO                                           19.9
             VERÃO                                           19.8
             VERÃO                                           19.5
             VERÃO                                           19.2
...                                                           ...
2023 12  31  PRIMAVERA                                       26.0
             PRIMAVERA                                       25.8
             PRIMAVERA                                       25.5
             PRIMAVERA                                       23.4
             PRIMAVERA                                       22.3

                                                                         \
                       TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                                 18.9
             VERÃO                                                 18.8
             VERÃO                                                 18.8
             VERÃO                                                 18.6
             VERÃO                                                 18.5
...                                                                 ...
2023 12  31  PRIMAVERA                                             19.0
             PRIMAVERA                                             18.2
             PRIMAVERA                                             18.0
             PRIMAVERA                                             18.2
             PRIMAVERA                                             18.6

                                                                         \
                       TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                                 18.7
             VERÃO                                                 18.5
             VERÃO                                                 18.4
             VERÃO                                                 18.4
             VERÃO                                                 18.0
...                                                                 ...
2023 12  31  PRIMAVERA                                             16.9
             PRIMAVERA                                             16.9
             PRIMAVERA                                             16.9
             PRIMAVERA                                             17.4
             PRIMAVERA                                             18.3

                                                        UMIDADE  \
                       UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                         91.0
             VERÃO                                         92.0
             VERÃO                                         92.0
             VERÃO                                         94.0
             VERÃO                                         94.0
...                                                         ...
2023 12  31  PRIMAVERA                                     64.0
             PRIMAVERA                                     62.0
             PRIMAVERA                                     62.0
             PRIMAVERA                                     72.0
             PRIMAVERA                                     79.0

                                                                 \
                       UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                         90.0
             VERÃO                                         91.0
             VERÃO                                         92.0
             VERÃO                                         92.0
             VERÃO                                         93.0
...                                                         ...
2023 12  31  PRIMAVERA                                     52.0
             PRIMAVERA                                     53.0
             PRIMAVERA                                     52.0
             PRIMAVERA                                     61.0
             PRIMAVERA                                     73.0

                                                            \
                       UMIDADE RELATIVA DO AR, HORARIA (%)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                    91.0
             VERÃO                                    92.0
             VERÃO                                    92.0
             VERÃO                                    94.0
             VERÃO                                    93.0
...                                                    ...
2023 12  31  PRIMAVERA                                63.0
             PRIMAVERA                                56.0
             PRIMAVERA                                61.0
             PRIMAVERA                                72.0
             PRIMAVERA                                78.0

                                        VELOCIDADE DO VENTO  \
                       VENTO, DIREÇÃO HORARIA (gr) (° (gr))
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                    308.0
             VERÃO                                    302.0
             VERÃO                                    302.0
             VERÃO                                    295.0
             VERÃO                                    313.0
...                                                     ...
2023 12  31  PRIMAVERA                                  1.0
             PRIMAVERA                                314.0
             PRIMAVERA                                300.0
             PRIMAVERA                                293.0
             PRIMAVERA                                285.0

                                                   \
                       VENTO, RAJADA MAXIMA (m/s)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                            2.1
             VERÃO                            2.2
             VERÃO                            2.7
             VERÃO                            3.4
             VERÃO                            3.9
...                                           ...
2023 12  31  PRIMAVERA                        5.3
             PRIMAVERA                        5.2
             PRIMAVERA                        5.1
             PRIMAVERA                        4.8
             PRIMAVERA                        3.7


                       VENTO, VELOCIDADE HORARIA (m/s)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                 1.4
             VERÃO                                 1.3
             VERÃO                                 1.6
             VERÃO                                 2.0
             VERÃO                                 2.5
...                                                ...
2023 12  31  PRIMAVERA                             2.1
             PRIMAVERA                             1.9
             PRIMAVERA                             2.7
             PRIMAVERA                             2.0
             PRIMAVERA                             1.4

[26280 rows x 19 columns]

In [223]:
df.groupby(["ANO","ESTAÇÃO"])["TEMPERATURA"].agg(["min","max","mean"])

                                                TEMPERATURA                    \
               TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
                                                        min   max        mean
ANO  ESTAÇÃO
2003 INVERNO                                        -9999.0  33.0 -564.520018
     OUTONO                                         -9999.0  28.8 -630.989789
     PRIMAVERA                                      -9999.0  32.7 -263.724774
     VERÃO                                          -9999.0  29.1 -827.319815
2013 INVERNO                                           11.0  32.6   21.005933
     OUTONO                                         -9999.0  28.1   11.288645
     PRIMAVERA                                         14.3  31.0   21.598958
     VERÃO                                          -9999.0  30.2  -61.525648
2023 INVERNO                                            9.6  33.5   21.921034
     OUTONO                                            10.3  29.0   20.101877
     PRIMAVERA                                         16.5  34.4   24.031927
     VERÃO                                             14.9  30.4   21.745139

                                                                       \
               TEMPERATURA DO PONTO DE ORVALHO (°C)
                                                min   max        mean
ANO  ESTAÇÃO
2003 INVERNO                                -9999.0  17.4 -574.933243
     OUTONO                                 -9999.0  19.5 -637.854075
     PRIMAVERA                              -9999.0  19.6 -270.725543
     VERÃO                                  -9999.0  20.1 -831.401806
2013 INVERNO                                   -1.6  19.0    9.566033
     OUTONO                                 -9999.0  20.4    5.290614
     PRIMAVERA                                  6.5  20.4   16.082971
     VERÃO                                  -9999.0  20.5  -66.546065
2023 INVERNO                                   -1.1  19.3   10.382366
     OUTONO                                     5.2  20.4   13.680128
     PRIMAVERA                                  5.3  21.5   16.246304
     VERÃO                                     10.4  19.7   16.472824

                                                                             \
               TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
                                                      min   max        mean
ANO  ESTAÇÃO
2003 INVERNO                                      -9999.0  33.2 -600.226585
     OUTONO                                       -9999.0  29.6 -676.317353
     PRIMAVERA                                    -9999.0  33.1 -285.867889
     VERÃO                                        -9999.0  30.0 -882.490463
2013 INVERNO                                         11.8  32.7   21.820335
     OUTONO                                       -9999.0  28.8   11.958700
     PRIMAVERA                                       14.4  31.9   22.247600
     VERÃO                                        -9999.0  31.1  -60.876528
2023 INVERNO                                         10.7  34.2   22.792364
     OUTONO                                          10.7  29.8   20.872161
     PRIMAVERA                                       17.2  34.6   24.813845
     VERÃO                                           15.4  30.9   22.442083

                                                                             \
               TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
                                                      min   max        mean
ANO  ESTAÇÃO
2003 INVERNO                                      -9999.0  32.4 -601.396196
     OUTONO                                       -9999.0  28.1 -677.431685
     PRIMAVERA                                    -9999.0  32.2 -286.938315
     VERÃO                                        -9999.0  28.8 -883.492222
2013 INVERNO                                         10.6  31.5   20.240942
     OUTONO                                       -9999.0  27.0   10.659158
     PRIMAVERA                                       14.1  29.7   20.996422
     VERÃO                                        -9999.0  29.2  -62.120417
2023 INVERNO                                          9.4  32.5   21.087000
     OUTONO                                          10.1  27.8   19.365064
     PRIMAVERA                                       15.8  33.0   23.273128
     VERÃO                                           14.3  29.7   21.086204

                                                                       \
               TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
                                                            min   max
ANO  ESTAÇÃO
2003 INVERNO                                            -9999.0  18.0
     OUTONO                                             -9999.0  19.9
     PRIMAVERA                                          -9999.0  20.7
     VERÃO                                              -9999.0  20.8
2013 INVERNO                                               -0.4  19.6
     OUTONO                                             -9999.0  21.0
     PRIMAVERA                                              7.2  21.3
     VERÃO                                              -9999.0  21.3
2023 INVERNO                                                0.0  19.5
     OUTONO                                                 7.2  20.9
     PRIMAVERA                                              6.0  22.3
     VERÃO                                                 11.7  20.1

                                                                             \
                           TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
                      mean                                              min
ANO  ESTAÇÃO
2003 INVERNO   -610.773596                                          -9999.0
     OUTONO    -683.273718                                          -9999.0
     PRIMAVERA -292.852717                                          -9999.0
     VERÃO     -886.594630                                          -9999.0
2013 INVERNO     10.100362                                             -1.9
     OUTONO       5.841804                                          -9999.0
     PRIMAVERA   16.719203                                              5.2
     VERÃO      -65.928009                                          -9999.0
2023 INVERNO     10.979682                                             -1.4
     OUTONO      14.249679                                              4.0
     PRIMAVERA   16.980890                                              5.1
     VERÃO       17.088333                                              8.3



                 max        mean
ANO  ESTAÇÃO
2003 INVERNO    16.5 -611.646286
     OUTONO     19.1 -684.117674
     PRIMAVERA  19.0 -293.937681
     VERÃO      19.6 -887.503102
2013 INVERNO    17.7    9.056748
     OUTONO     19.9    4.789927
     PRIMAVERA  19.8   15.482201
     VERÃO      19.8  -67.131944
2023 INVERNO    19.3    9.838864
     OUTONO     19.4   13.163645
     PRIMAVERA  21.3   15.567000
     VERÃO      18.9   15.889120

In [224]:
df.groupby(["ANO","ESTAÇÃO"])["PRECIPITAÇÃO TOTAL, HORÁRIO (mm)"].agg(["min","max","mean"])

                   min   max        mean
ANO  ESTAÇÃO
2003 INVERNO   -9999.0   7.6 -584.159873
     OUTONO    -9999.0  24.8 -650.079762
     PRIMAVERA -9999.0  33.4 -285.107971
     VERÃO     -9999.0  29.4 -846.932593
2013 INVERNO       0.0  24.8    0.026540
     OUTONO    -9999.0  11.2   -9.103480
     PRIMAVERA -9999.0  30.8   -4.237591
     VERÃO     -9999.0  40.2  -82.964630
2023 INVERNO       0.0  16.6    0.030644
     OUTONO        0.0  23.4    0.087546
     PRIMAVERA     0.0  21.4    0.161542
     VERÃO         0.0  18.2    0.176389

In [225]:

df["HORA (UTC)"] = df["HORA (UTC)"].apply(lambda x: int(str(x)[0:2]))

In [226]:
df

                       DATA (YYYY-MM-DD) HORA (UTC)  \

ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO            2003-01-01          0
             VERÃO            2003-01-01          1
             VERÃO            2003-01-01          2
             VERÃO            2003-01-01          3
             VERÃO            2003-01-01          4
...                                  ...        ...
2023 12  31  PRIMAVERA        2023/12/31         19
             PRIMAVERA        2023/12/31         20
             PRIMAVERA        2023/12/31         21
             PRIMAVERA        2023/12/31         22
             PRIMAVERA        2023/12/31         23

                       PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \

ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                  0.0
             VERÃO                                  0.0
             VERÃO                                  0.0
             VERÃO                                  0.0
             VERÃO                                  0.0
...                                                 ...
2023 12  31  PRIMAVERA                              0.0
             PRIMAVERA                              0.0
             PRIMAVERA                              0.0
             PRIMAVERA                              0.0
             PRIMAVERA                              0.0

                                                                     PRESSÃO  \
                       PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                                  886.9
             VERÃO                                                  887.3
             VERÃO                                                  887.8
             VERÃO                                                  886.9
             VERÃO                                                  886.8
...                                                                   ...
2023 12  31  PRIMAVERA                                              884.2
             PRIMAVERA                                              883.7
             PRIMAVERA                                              883.5
             PRIMAVERA                                              884.5
             PRIMAVERA                                              885.3

                                                                        \
                       PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                               887.0
             VERÃO                                               887.3
             VERÃO                                               887.8
             VERÃO                                               887.8
             VERÃO                                               886.9
...                                                                ...
2023 12  31  PRIMAVERA                                           885.2
             PRIMAVERA                                           884.3
             PRIMAVERA                                           883.7
             PRIMAVERA                                           884.5
             PRIMAVERA                                           885.3

                                                                         \
                       PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                                886.5
             VERÃO                                                886.9
             VERÃO                                                887.3
             VERÃO                                                886.9
             VERÃO                                                886.7
...                                                                 ...
2023 12  31  PRIMAVERA                                            884.2
             PRIMAVERA                                            883.7
             PRIMAVERA                                            883.4
             PRIMAVERA                                            883.5
             PRIMAVERA                                            884.5

                       RADIACAO GLOBAL (KJ/m²)  \

ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                     -9999.0
             VERÃO                     -9999.0
             VERÃO                     -9999.0
             VERÃO                     -9999.0
             VERÃO                     -9999.0
...                                        ...
2023 12  31  PRIMAVERA                  1252.2
             PRIMAVERA                  1178.8
             PRIMAVERA                   873.0
             PRIMAVERA                   104.0
             PRIMAVERA                     NaN

                                                        TEMPERATURA  \
                       TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                             20.3
             VERÃO                                             19.9
             VERÃO                                             19.8
             VERÃO                                             19.5
             VERÃO                                             19.2
...                                                             ...
2023 12  31  PRIMAVERA                                         26.1
             PRIMAVERA                                         27.7
             PRIMAVERA                                         25.5
             PRIMAVERA                                         23.4
             PRIMAVERA                                         22.6

                                                             \
                       TEMPERATURA DO PONTO DE ORVALHO (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                     18.8
             VERÃO                                     18.5
             VERÃO                                     18.5
             VERÃO                                     18.5
             VERÃO                                     18.0
...                                                     ...
2023 12  31  PRIMAVERA                                 18.4
             PRIMAVERA                                 18.1
             PRIMAVERA                                 17.4
             PRIMAVERA                                 18.2
             PRIMAVERA                                 18.6

                                                                   \
                       TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                           20.4
             VERÃO                                           20.3
             VERÃO                                           20.1
             VERÃO                                           19.8
             VERÃO                                           19.5
...                                                           ...
2023 12  31  PRIMAVERA                                       28.1
             PRIMAVERA                                       27.7
             PRIMAVERA                                       27.7
             PRIMAVERA                                       25.5
             PRIMAVERA                                       23.4

                                                                   \
                       TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                           20.2
             VERÃO                                           19.9
             VERÃO                                           19.8
             VERÃO                                           19.5
             VERÃO                                           19.2
...                                                           ...
2023 12  31  PRIMAVERA                                       26.0
             PRIMAVERA                                       25.8
             PRIMAVERA                                       25.5
             PRIMAVERA                                       23.4
             PRIMAVERA                                       22.3

                                                                         \
                       TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                                 18.9
             VERÃO                                                 18.8
             VERÃO                                                 18.8
             VERÃO                                                 18.6
             VERÃO                                                 18.5
...                                                                 ...
2023 12  31  PRIMAVERA                                             19.0
             PRIMAVERA                                             18.2
             PRIMAVERA                                             18.0
             PRIMAVERA                                             18.2
             PRIMAVERA                                             18.6

                                                                         \
                       TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                                 18.7
             VERÃO                                                 18.5
             VERÃO                                                 18.4
             VERÃO                                                 18.4
             VERÃO                                                 18.0
...                                                                 ...
2023 12  31  PRIMAVERA                                             16.9
             PRIMAVERA                                             16.9
             PRIMAVERA                                             16.9
             PRIMAVERA                                             17.4
             PRIMAVERA                                             18.3

                                                        UMIDADE  \
                       UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                         91.0
             VERÃO                                         92.0
             VERÃO                                         92.0
             VERÃO                                         94.0
             VERÃO                                         94.0
...                                                         ...
2023 12  31  PRIMAVERA                                     64.0
             PRIMAVERA                                     62.0
             PRIMAVERA                                     62.0
             PRIMAVERA                                     72.0
             PRIMAVERA                                     79.0

                                                                 \
                       UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                         90.0
             VERÃO                                         91.0
             VERÃO                                         92.0
             VERÃO                                         92.0
             VERÃO                                         93.0
...                                                         ...
2023 12  31  PRIMAVERA                                     52.0
             PRIMAVERA                                     53.0
             PRIMAVERA                                     52.0
             PRIMAVERA                                     61.0
             PRIMAVERA                                     73.0

                                                            \
                       UMIDADE RELATIVA DO AR, HORARIA (%)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                    91.0
             VERÃO                                    92.0
             VERÃO                                    92.0
             VERÃO                                    94.0
             VERÃO                                    93.0
...                                                    ...
2023 12  31  PRIMAVERA                                63.0
             PRIMAVERA                                56.0
             PRIMAVERA                                61.0
             PRIMAVERA                                72.0
             PRIMAVERA                                78.0

                                        VELOCIDADE DO VENTO  \
                       VENTO, DIREÇÃO HORARIA (gr) (° (gr))
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                    308.0
             VERÃO                                    302.0
             VERÃO                                    302.0
             VERÃO                                    295.0
             VERÃO                                    313.0
...                                                     ...
2023 12  31  PRIMAVERA                                  1.0
             PRIMAVERA                                314.0
             PRIMAVERA                                300.0
             PRIMAVERA                                293.0
             PRIMAVERA                                285.0

                                                   \
                       VENTO, RAJADA MAXIMA (m/s)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                            2.1
             VERÃO                            2.2
             VERÃO                            2.7
             VERÃO                            3.4
             VERÃO                            3.9
...                                           ...
2023 12  31  PRIMAVERA                        5.3
             PRIMAVERA                        5.2
             PRIMAVERA                        5.1
             PRIMAVERA                        4.8
             PRIMAVERA                        3.7


                       VENTO, VELOCIDADE HORARIA (m/s)
ANO  MES DIA ESTAÇÃO
2003 1   1   VERÃO                                 1.4
             VERÃO                                 1.3
             VERÃO                                 1.6
             VERÃO                                 2.0
             VERÃO                                 2.5
...                                                ...
2023 12  31  PRIMAVERA                             2.1
             PRIMAVERA                             1.9
             PRIMAVERA                             2.7
             PRIMAVERA                             2.0
             PRIMAVERA                             1.4

[26280 rows x 19 columns]

In [227]:
def hrParaIntervalo(hr):
    if hr <= 6:
        return "MADRUGADA"
    if hr <= 12:
        return "MANHÃ"
    if hr <= 18:
        return "TARDE"
    return "NOITE"

df["INTERVALO"] = df["HORA (UTC)"].apply(hrParaIntervalo)
df = df.set_index('INTERVALO', append=True)

In [228]:
df

                                 DATA (YYYY-MM-DD) HORA (UTC)  \

ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA        2003-01-01          0
                       MADRUGADA        2003-01-01          1
                       MADRUGADA        2003-01-01          2
                       MADRUGADA        2003-01-01          3
                       MADRUGADA        2003-01-01          4
...                                            ...        ...
2023 12  31  PRIMAVERA NOITE            2023/12/31         19
                       NOITE            2023/12/31         20
                       NOITE            2023/12/31         21
                       NOITE            2023/12/31         22
                       NOITE            2023/12/31         23

                                 PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \

ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                              0.0
                       MADRUGADA                              0.0
                       MADRUGADA                              0.0
                       MADRUGADA                              0.0
                       MADRUGADA                              0.0
...                                                           ...
2023 12  31  PRIMAVERA NOITE                                  0.0
                       NOITE                                  0.0
                       NOITE                                  0.0
                       NOITE                                  0.0
                       NOITE                                  0.0

                                                                               PRESSÃO  \
                                 PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                              886.9
                       MADRUGADA                                              887.3
                       MADRUGADA                                              887.8
                       MADRUGADA                                              886.9
                       MADRUGADA                                              886.8
...                                                                             ...
2023 12  31  PRIMAVERA NOITE                                                  884.2
                       NOITE                                                  883.7
                       NOITE                                                  883.5
                       NOITE                                                  884.5
                       NOITE                                                  885.3

                                                                                  \
                                 PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                           887.0
                       MADRUGADA                                           887.3
                       MADRUGADA                                           887.8
                       MADRUGADA                                           887.8
                       MADRUGADA                                           886.9
...                                                                          ...
2023 12  31  PRIMAVERA NOITE                                               885.2
                       NOITE                                               884.3
                       NOITE                                               883.7
                       NOITE                                               884.5
                       NOITE                                               885.3

                                                                                   \
                                 PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                            886.5
                       MADRUGADA                                            886.9
                       MADRUGADA                                            887.3
                       MADRUGADA                                            886.9
                       MADRUGADA                                            886.7
...                                                                           ...
2023 12  31  PRIMAVERA NOITE                                                884.2
                       NOITE                                                883.7
                       NOITE                                                883.4
                       NOITE                                                883.5
                       NOITE                                                884.5

                                 RADIACAO GLOBAL (KJ/m²)  \

ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                 -9999.0
                       MADRUGADA                 -9999.0
                       MADRUGADA                 -9999.0
                       MADRUGADA                 -9999.0
                       MADRUGADA                 -9999.0
...                                                  ...
2023 12  31  PRIMAVERA NOITE                      1252.2
                       NOITE                      1178.8
                       NOITE                       873.0
                       NOITE                       104.0
                       NOITE                         NaN

                                                                  TEMPERATURA  \
                                 TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                         20.3
                       MADRUGADA                                         19.9
                       MADRUGADA                                         19.8
                       MADRUGADA                                         19.5
                       MADRUGADA                                         19.2
...                                                                       ...
2023 12  31  PRIMAVERA NOITE                                             26.1
                       NOITE                                             27.7
                       NOITE                                             25.5
                       NOITE                                             23.4
                       NOITE                                             22.6

                                                                       \
                                 TEMPERATURA DO PONTO DE ORVALHO (°C)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                 18.8
                       MADRUGADA                                 18.5
                       MADRUGADA                                 18.5
                       MADRUGADA                                 18.5
                       MADRUGADA                                 18.0
...                                                               ...
2023 12  31  PRIMAVERA NOITE                                     18.4
                       NOITE                                     18.1
                       NOITE                                     17.4
                       NOITE                                     18.2
                       NOITE                                     18.6

                                                                             \
                                 TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                       20.4
                       MADRUGADA                                       20.3
                       MADRUGADA                                       20.1
                       MADRUGADA                                       19.8
                       MADRUGADA                                       19.5
...                                                                     ...
2023 12  31  PRIMAVERA NOITE                                           28.1
                       NOITE                                           27.7
                       NOITE                                           27.7
                       NOITE                                           25.5
                       NOITE                                           23.4

                                                                             \
                                 TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                       20.2
                       MADRUGADA                                       19.9
                       MADRUGADA                                       19.8
                       MADRUGADA                                       19.5
                       MADRUGADA                                       19.2
...                                                                     ...
2023 12  31  PRIMAVERA NOITE                                           26.0
                       NOITE                                           25.8
                       NOITE                                           25.5
                       NOITE                                           23.4
                       NOITE                                           22.3

                                                                                   \
                                 TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                             18.9
                       MADRUGADA                                             18.8
                       MADRUGADA                                             18.8
                       MADRUGADA                                             18.6
                       MADRUGADA                                             18.5
...                                                                           ...
2023 12  31  PRIMAVERA NOITE                                                 19.0
                       NOITE                                                 18.2
                       NOITE                                                 18.0
                       NOITE                                                 18.2
                       NOITE                                                 18.6

                                                                                   \
                                 TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                             18.7
                       MADRUGADA                                             18.5
                       MADRUGADA                                             18.4
                       MADRUGADA                                             18.4
                       MADRUGADA                                             18.0
...                                                                           ...
2023 12  31  PRIMAVERA NOITE                                                 16.9
                       NOITE                                                 16.9
                       NOITE                                                 16.9
                       NOITE                                                 17.4
                       NOITE                                                 18.3

                                                                  UMIDADE  \
                                 UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                     91.0
                       MADRUGADA                                     92.0
                       MADRUGADA                                     92.0
                       MADRUGADA                                     94.0
                       MADRUGADA                                     94.0
...                                                                   ...
2023 12  31  PRIMAVERA NOITE                                         64.0
                       NOITE                                         62.0
                       NOITE                                         62.0
                       NOITE                                         72.0
                       NOITE                                         79.0

                                                                           \
                                 UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                     90.0
                       MADRUGADA                                     91.0
                       MADRUGADA                                     92.0
                       MADRUGADA                                     92.0
                       MADRUGADA                                     93.0
...                                                                   ...
2023 12  31  PRIMAVERA NOITE                                         52.0
                       NOITE                                         53.0
                       NOITE                                         52.0
                       NOITE                                         61.0
                       NOITE                                         73.0

                                                                      \
                                 UMIDADE RELATIVA DO AR, HORARIA (%)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                91.0
                       MADRUGADA                                92.0
                       MADRUGADA                                92.0
                       MADRUGADA                                94.0
                       MADRUGADA                                93.0
...                                                              ...
2023 12  31  PRIMAVERA NOITE                                    63.0
                       NOITE                                    56.0
                       NOITE                                    61.0
                       NOITE                                    72.0
                       NOITE                                    78.0

                                                  VELOCIDADE DO VENTO  \
                                 VENTO, DIREÇÃO HORARIA (gr) (° (gr))
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                                308.0
                       MADRUGADA                                302.0
                       MADRUGADA                                302.0
                       MADRUGADA                                295.0
                       MADRUGADA                                313.0
...                                                               ...
2023 12  31  PRIMAVERA NOITE                                      1.0
                       NOITE                                    314.0
                       NOITE                                    300.0
                       NOITE                                    293.0
                       NOITE                                    285.0

                                                             \
                                 VENTO, RAJADA MAXIMA (m/s)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                        2.1
                       MADRUGADA                        2.2
                       MADRUGADA                        2.7
                       MADRUGADA                        3.4
                       MADRUGADA                        3.9
...                                                     ...
2023 12  31  PRIMAVERA NOITE                            5.3
                       NOITE                            5.2
                       NOITE                            5.1
                       NOITE                            4.8
                       NOITE                            3.7


                                 VENTO, VELOCIDADE HORARIA (m/s)
ANO  MES DIA ESTAÇÃO   INTERVALO
2003 1   1   VERÃO     MADRUGADA                             1.4
                       MADRUGADA                             1.3
                       MADRUGADA                             1.6
                       MADRUGADA                             2.0
                       MADRUGADA                             2.5
...                                                          ...
2023 12  31  PRIMAVERA NOITE                                 2.1
                       NOITE                                 1.9
                       NOITE                                 2.7
                       NOITE                                 2.0
                       NOITE                                 1.4

[26280 rows x 19 columns]

In [231]:
df.xs(28, level="DIA").xs(9, level="MES").groupby(["ANO","INTERVALO"])["TEMPERATURA"].agg(["min","max","mean"])

                                                TEMPERATURA                   \
               TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
                                                        min   max       mean
ANO  INTERVALO
2003 MADRUGADA                                         20.5  21.8  21.228571
     MANHÃ                                             20.1  21.4  20.600000
     NOITE                                             20.0  25.0  22.760000
     TARDE                                             22.6  23.9  23.116667
2013 MADRUGADA                                         22.0  26.8  24.157143
     MANHÃ                                             21.4  23.5  22.200000
     NOITE                                             22.4  24.1  23.380000
     TARDE                                             24.7  28.5  26.583333
2023 MADRUGADA                                         22.1  23.6  22.728571
     MANHÃ                                             21.1  25.9  22.333333
     NOITE                                             24.3  26.0  25.300000
     TARDE                                             27.0  32.3  29.616667

                                                                      \
               TEMPERATURA DO PONTO DE ORVALHO (°C)
                                                min   max       mean
ANO  INTERVALO
2003 MADRUGADA                                 13.0  14.8  14.100000
     MANHÃ                                     13.2  15.6  14.333333
     NOITE                                     13.4  14.7  13.980000
     TARDE                                     12.9  16.1  13.816667
2013 MADRUGADA                                 11.8  14.1  12.942857
     MANHÃ                                     13.0  15.4  14.566667
     NOITE                                     16.1  19.0  17.740000
     TARDE                                     13.4  15.7  14.883333
2023 MADRUGADA                                 17.6  18.2  17.842857
     MANHÃ                                     17.6  18.5  18.233333
     NOITE                                     14.7  15.2  15.000000
     TARDE                                     15.8  17.6  16.800000

                                                                            \
               TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
                                                      min   max       mean
ANO  INTERVALO
2003 MADRUGADA                                       21.1  22.4  21.800000
     MANHÃ                                           20.6  21.6  21.133333
     NOITE                                           20.9  25.1  23.800000
     TARDE                                           22.7  23.9  23.350000
2013 MADRUGADA                                       22.5  27.1  24.971429
     MANHÃ                                           21.7  23.5  22.500000
     NOITE                                           23.4  24.8  24.120000
     TARDE                                           25.1  29.5  28.033333
2023 MADRUGADA                                       22.7  23.8  23.142857
     MANHÃ                                           21.3  26.1  22.583333
     NOITE                                           25.2  32.4  27.260000
     TARDE                                           27.8  32.3  30.183333

                                                                            \
               TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
                                                      min   max       mean
ANO  INTERVALO
2003 MADRUGADA                                       20.5  21.6  20.957143
     MANHÃ                                           19.9  20.5  20.250000
     NOITE                                           19.8  24.1  22.500000
     TARDE                                           21.5  23.0  22.366667
2013 MADRUGADA                                       21.9  26.3  23.928571
     MANHÃ                                           21.0  22.8  21.683333
     NOITE                                           22.0  23.6  22.600000
     TARDE                                           23.4  27.0  25.500000
2023 MADRUGADA                                       21.6  23.6  22.485714
     MANHÃ                                           20.7  22.4  21.450000
     NOITE                                           24.0  25.9  25.020000
     TARDE                                           25.4  30.4  28.383333

                                                                       \
               TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
                                                            min   max
ANO  INTERVALO
2003 MADRUGADA                                             13.7  15.1
     MANHÃ                                                 13.9  16.3
     NOITE                                                 13.6  15.1
     TARDE                                                 14.0  16.9
2013 MADRUGADA                                             12.0  14.3
     MANHÃ                                                 13.6  15.6
     NOITE                                                 17.2  19.5
     TARDE                                                 14.9  16.4
2023 MADRUGADA                                             17.7  18.2
     MANHÃ                                                 18.1  18.9
     NOITE                                                 15.2  15.7
     TARDE                                                 17.2  19.0

                                                                            \
                          TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
                     mean                                              min
ANO  INTERVALO
2003 MADRUGADA  14.571429                                             12.6
     MANHÃ      14.833333                                             12.0
     NOITE      14.260000                                             12.4
     TARDE      15.266667                                             12.4
2013 MADRUGADA  13.328571                                             11.2
     MANHÃ      14.750000                                             12.8
     NOITE      18.780000                                             14.1
     TARDE      15.783333                                             12.9
2023 MADRUGADA  18.014286                                             17.5
     MANHÃ      18.550000                                             17.6
     NOITE      15.500000                                             13.4
     TARDE      17.833333                                             15.1



                 max       mean
ANO  INTERVALO
2003 MADRUGADA  14.3  13.542857
     MANHÃ      14.2  13.266667
     NOITE      14.4  13.380000
     TARDE      14.8  13.266667
2013 MADRUGADA  13.6  12.385714
     MANHÃ      15.0  14.000000
     NOITE      17.7  16.400000
     TARDE      15.0  14.050000
2023 MADRUGADA  18.0  17.700000
     MANHÃ      18.4  18.066667
     NOITE      15.0  14.140000
     TARDE      17.0  16.166667

In [232]:
df.xs(28, level="DIA").xs(9, level="MES").groupby(["ANO","INTERVALO"])["PRECIPITAÇÃO TOTAL, HORÁRIO (mm)"].agg(["min","max","mean"])

                min  max      mean
ANO  INTERVALO
2003 MADRUGADA  0.0  0.0  0.000000
     MANHÃ      0.0  0.4  0.066667
     NOITE      0.0  0.0  0.000000
     TARDE      0.0  0.0  0.000000
2013 MADRUGADA  0.0  0.0  0.000000
     MANHÃ      0.0  0.0  0.000000
     NOITE      0.0  1.6  0.480000
     TARDE      0.0  0.0  0.000000
2023 MADRUGADA  0.0  0.0  0.000000
     MANHÃ      0.0  0.2  0.033333
     NOITE      0.0  0.0  0.000000
     TARDE      0.0  0.0  0.000000