Exercício 1: Carregando e analisando um DataSet

In [1]:
import pandas as pd

In [2]:
brasilia2003 = pd.read_csv('arquivos/INMET_CO_DF_A001_BRASILIA_01-01-2003_A_31-12-2003.CSV', encoding='latin1', sep=';', skiprows=8)
brasilia2013 = pd.read_csv('arquivos/INMET_CO_DF_A001_BRASILIA_01-01-2013_A_31-12-2013.CSV',  encoding='latin1', sep=';', skiprows=8)
brasilia2023 = pd.read_csv('arquivos/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023.CSV',  encoding='latin1', sep=';', skiprows=8)
brasilia2003.head(6)

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2003-01-01,00:00,0,"886,9",887,"886,5",-9999,"20,3","18,8","20,4","20,2","18,9","18,7",91,90,91,308,"2,1","1,4",NaN
1,2003-01-01,01:00,0,"887,3","887,3","886,9",-9999,"19,9","18,5","20,3","19,9","18,8","18,5",92,91,92,302,"2,2","1,3",NaN
2,2003-01-01,02:00,0,"887,8","887,8","887,3",-9999,"19,8","18,5","20,1","19,8","18,8","18,4",92,92,92,302,"2,7","1,6",NaN
3,2003-01-01,03:00,0,"886,9","887,8","886,9",-9999,"19,5","18,5","19,8","19,5","18,6","18,4",94,92,94,295,"3,4",2,NaN
4,2003-01-01,04:00,0,"886,8","886,9","886,7",-9999,"19,2",18,"19,5","19,2","18,5",18,94,93,93,313,"3,9","2,5",NaN
5,2003-01-01,05:00,0,"886,4","886,9","886,4",-9999,"18,9","18,1","19,2","18,8","18,1","17,9",95,93,95,325,"4,5","2,2",NaN

In [3]:
brasilia2013.head(6)

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2013-01-01,00:00,0,"885,7","885,7","885,1",-9999,"24,1","14,2",25,"24,1","14,4","13,9",54,50,54,112,"4,6","2,3",NaN
1,2013-01-01,01:00,0,"886,5","886,5","885,7",-9999,"23,5","14,5","24,2","23,4","14,6","14,2",58,54,57,110,5,"2,7",NaN
2,2013-01-01,02:00,0,"886,9","886,9","886,5",-9999,"23,3","14,5","23,5","23,2","14,7","14,4",59,56,58,91,"5,4","3,4",NaN
3,2013-01-01,03:00,0,"886,5","886,9","886,5",-9999,"22,8","14,6","23,3","22,8","14,7","14,4",60,57,60,81,"5,4","3,1",NaN
4,2013-01-01,04:00,0,886,"886,5",886,-9999,"22,4","14,5","22,9","22,2","14,6","14,3",62,59,61,86,"5,3","2,9",NaN
5,2013-01-01,05:00,0,"885,6",886,"885,6",-9999,"21,6","14,5","22,4","21,6","14,6","14,4",64,61,64,101,5,"1,9",NaN

In [4]:
brasilia2023.head(6)

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,0,"887,7","887,7","887,2",NaN,"20,1","17,9","20,9",20,"19,2","17,8",91.0,87.0,87.0,187.0,"3,3","1,2",NaN
1,2023/01/01,0100 UTC,0,"888,1","888,1","887,7",NaN,"19,2","17,5","20,1","19,2","17,8","17,4",90.0,87.0,90.0,153.0,"2,9",",8",NaN
2,2023/01/01,0200 UTC,0,"887,8","888,1","887,8",NaN,"19,3","17,6","19,5",19,"17,8","17,3",90.0,89.0,90.0,145.0,"2,5","1,5",NaN
3,2023/01/01,0300 UTC,0,"887,8","887,9","887,7",NaN,"19,3","17,7","19,4","19,1","17,8","17,5",91.0,90.0,91.0,162.0,"3,2","1,4",NaN
4,2023/01/01,0400 UTC,0,"887,6","887,9","887,6",NaN,"19,7","18,1","19,7","19,1","18,1","17,4",91.0,90.0,90.0,140.0,"5,7","2,7",NaN
5,2023/01/01,0500 UTC,0,"886,7","887,6","886,7",NaN,"19,1","17,7","19,7","19,1","18,1","17,7",92.0,90.0,92.0,128.0,"7,1",2,NaN

Exercício 2: Juntando os datasets

Padronizando as colunas

In [15]:
brasilia2023.rename(columns={'Data':'DATA (YYYY-MM-DD)', 'Hora UTC':'HORA (UTC)', 'RADIACAO GLOBAL (Kj/m²)': 'RADIACAO GLOBAL (KJ/m²)'}, inplace=True)
brasilia2023['DATA (YYYY-MM-DD)'] = pd.to_datetime(brasilia2023['DATA (YYYY-MM-DD)'], format="%Y/%m/%d", errors='coerce')

Gerando MultiIndex de Ano, Meses e Dias

In [19]:
brasilia = pd.concat([brasilia2003, brasilia2013, brasilia2023])
brasilia['DATA (YYYY-MM-DD)'] = pd.to_datetime(brasilia['DATA (YYYY-MM-DD)'])
colunaData = pd.DatetimeIndex(brasilia['DATA (YYYY-MM-DD)'])
brasilia['Ano'] = colunaData.year
brasilia['Mes'] = colunaData.month
brasilia['Dia'] = colunaData.day
#print(brasilia.dtypes)
brasilia.set_index(['Ano', 'Mes', 'Dia'], inplace=True)
brasilia.drop(['DATA (YYYY-MM-DD)'], axis=1, inplace=True)

brasilia

             HORA (UTC) PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \
Ano  Mes Dia
2003 1   1        00:00                                0
         1        01:00                                0
         1        02:00                                0
         1        03:00                                0
         1        04:00                                0
...                 ...                              ...
2023 12  31    1900 UTC                                0
         31    2000 UTC                                0
         31    2100 UTC                                0
         31    2200 UTC                                0
         31    2300 UTC                                0

             PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)  \
Ano  Mes Dia
2003 1   1                                                886,9
         1                                                887,3
         1                                                887,8
         1                                                886,9
         1                                                886,8
...                                                         ...
2023 12  31                                               884,2
         31                                               883,7
         31                                               883,5
         31                                               884,5
         31                                               885,3

             PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)  \
Ano  Mes Dia
2003 1   1                                               887
         1                                             887,3
         1                                             887,8
         1                                             887,8
         1                                             886,9
...                                                      ...
2023 12  31                                            885,2
         31                                            884,3
         31                                            883,7
         31                                            884,5
         31                                            885,3

             PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)  \
Ano  Mes Dia
2003 1   1                                              886,5
         1                                              886,9
         1                                              887,3
         1                                              886,9
         1                                              886,7
...                                                       ...
2023 12  31                                             884,2
         31                                             883,7
         31                                             883,4
         31                                             883,5
         31                                             884,5

             RADIACAO GLOBAL (KJ/m²)  \
Ano  Mes Dia
2003 1   1                     -9999
         1                     -9999
         1                     -9999
         1                     -9999
         1                     -9999
...                              ...
2023 12  31                   1252,2
         31                   1178,8
         31                      873
         31                      104
         31                      NaN

             TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)  \
Ano  Mes Dia
2003 1   1                                           20,3
         1                                           19,9
         1                                           19,8
         1                                           19,5
         1                                           19,2
...                                                   ...
2023 12  31                                          26,1
         31                                          27,7
         31                                          25,5
         31                                          23,4
         31                                          22,6

             TEMPERATURA DO PONTO DE ORVALHO (°C)  \
Ano  Mes Dia
2003 1   1                                   18,8
         1                                   18,5
         1                                   18,5
         1                                   18,5
         1                                     18
...                                           ...
2023 12  31                                  18,4
         31                                  18,1
         31                                  17,4
         31                                  18,2
         31                                  18,6

             TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)  \
Ano  Mes Dia
2003 1   1                                         20,4
         1                                         20,3
         1                                         20,1
         1                                         19,8
         1                                         19,5
...                                                 ...
2023 12  31                                        28,1
         31                                        27,7
         31                                        27,7
         31                                        25,5
         31                                        23,4

             TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)  \
Ano  Mes Dia
2003 1   1                                         20,2
         1                                         19,9
         1                                         19,8
         1                                         19,5
         1                                         19,2
...                                                 ...
2023 12  31                                          26
         31                                        25,8
         31                                        25,5
         31                                        23,4
         31                                        22,3

             TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)  \
Ano  Mes Dia
2003 1   1                                               18,9
         1                                               18,8
         1                                               18,8
         1                                               18,6
         1                                               18,5
...                                                       ...
2023 12  31                                                19
         31                                              18,2
         31                                                18
         31                                              18,2
         31                                              18,6

             TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)  \
Ano  Mes Dia
2003 1   1                                               18,7
         1                                               18,5
         1                                               18,4
         1                                               18,4
         1                                                 18
...                                                       ...
2023 12  31                                              16,9
         31                                              16,9
         31                                              16,9
         31                                              17,4
         31                                              18,3

              UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)  \
Ano  Mes Dia
2003 1   1                                        91.0
         1                                        92.0
         1                                        92.0
         1                                        94.0
         1                                        94.0
...                                                ...
2023 12  31                                       64.0
         31                                       62.0
         31                                       62.0
         31                                       72.0
         31                                       79.0

              UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)  \
Ano  Mes Dia
2003 1   1                                        90.0
         1                                        91.0
         1                                        92.0
         1                                        92.0
         1                                        93.0
...                                                ...
2023 12  31                                       52.0
         31                                       53.0
         31                                       52.0
         31                                       61.0
         31                                       73.0

              UMIDADE RELATIVA DO AR, HORARIA (%)  \
Ano  Mes Dia
2003 1   1                                   91.0
         1                                   92.0
         1                                   92.0
         1                                   94.0
         1                                   93.0
...                                           ...
2023 12  31                                  63.0
         31                                  56.0
         31                                  61.0
         31                                  72.0
         31                                  78.0

              VENTO, DIREÇÃO HORARIA (gr) (° (gr)) VENTO, RAJADA MAXIMA (m/s)  \
Ano  Mes Dia
2003 1   1                                   308.0                        2,1
         1                                   302.0                        2,2
         1                                   302.0                        2,7
         1                                   295.0                        3,4
         1                                   313.0                        3,9
...                                            ...                        ...
2023 12  31                                    1.0                        5,3
         31                                  314.0                        5,2
         31                                  300.0                        5,1
         31                                  293.0                        4,8
         31                                  285.0                        3,7

             VENTO, VELOCIDADE HORARIA (m/s)  Unnamed: 19
Ano  Mes Dia
2003 1   1                               1,4          NaN
         1                               1,3          NaN
         1                               1,6          NaN
         1                                 2          NaN
         1                               2,5          NaN
...                                      ...          ...
2023 12  31                              2,1          NaN
         31                              1,9          NaN
         31                              2,7          NaN
         31                                2          NaN
         31                              1,4          NaN

[26280 rows x 19 columns]