In [2]:
import pandas as pd
df2003 = pd.read_csv("dadosBrasilia/INMET_CO_DF_A001_BRASILIA_01-01-2003_A_31-12-2003.CSV", encoding='iso-8859-1', decimal=',', delimiter=';', skiprows=8)
df2003.head()

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2003-01-01,00:00,0.0,886.9,887.0,886.5,-9999,20.3,18.8,20.4,20.2,18.9,18.7,91,90,91,308,2.1,1.4,NaN
1,2003-01-01,01:00,0.0,887.3,887.3,886.9,-9999,19.9,18.5,20.3,19.9,18.8,18.5,92,91,92,302,2.2,1.3,NaN
2,2003-01-01,02:00,0.0,887.8,887.8,887.3,-9999,19.8,18.5,20.1,19.8,18.8,18.4,92,92,92,302,2.7,1.6,NaN
3,2003-01-01,03:00,0.0,886.9,887.8,886.9,-9999,19.5,18.5,19.8,19.5,18.6,18.4,94,92,94,295,3.4,2.0,NaN
4,2003-01-01,04:00,0.0,886.8,886.9,886.7,-9999,19.2,18.0,19.5,19.2,18.5,18.0,94,93,93,313,3.9,2.5,NaN

In [3]:
df2013 = pd.read_csv("dadosBrasilia/INMET_CO_DF_A001_BRASILIA_01-01-2013_A_31-12-2013.CSV", encoding='iso-8859-1', decimal=',', delimiter=';', skiprows=8)
df2013.head()

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2013-01-01,00:00,0.0,885.7,885.7,885.1,-9999.0,24.1,14.2,25.0,24.1,14.4,13.9,54,50,54,112,4.6,2.3,NaN
1,2013-01-01,01:00,0.0,886.5,886.5,885.7,-9999.0,23.5,14.5,24.2,23.4,14.6,14.2,58,54,57,110,5.0,2.7,NaN
2,2013-01-01,02:00,0.0,886.9,886.9,886.5,-9999.0,23.3,14.5,23.5,23.2,14.7,14.4,59,56,58,91,5.4,3.4,NaN
3,2013-01-01,03:00,0.0,886.5,886.9,886.5,-9999.0,22.8,14.6,23.3,22.8,14.7,14.4,60,57,60,81,5.4,3.1,NaN
4,2013-01-01,04:00,0.0,886.0,886.5,886.0,-9999.0,22.4,14.5,22.9,22.2,14.6,14.3,62,59,61,86,5.3,2.9,NaN

In [4]:
df2023 = pd.read_csv("dadosBrasilia/INMET_CO_DF_A001_BRASILIA_01-01-2023_A_31-12-2023.CSV", encoding='iso-8859-1', decimal=',', delimiter=';', skiprows=8)
df2023.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,0000 UTC,0.0,887.7,887.7,887.2,NaN,20.1,17.9,20.9,20.0,19.2,17.8,91.0,87.0,87.0,187.0,3.3,1.2,NaN
1,2023/01/01,0100 UTC,0.0,888.1,888.1,887.7,NaN,19.2,17.5,20.1,19.2,17.8,17.4,90.0,87.0,90.0,153.0,2.9,0.8,NaN
2,2023/01/01,0200 UTC,0.0,887.8,888.1,887.8,NaN,19.3,17.6,19.5,19.0,17.8,17.3,90.0,89.0,90.0,145.0,2.5,1.5,NaN
3,2023/01/01,0300 UTC,0.0,887.8,887.9,887.7,NaN,19.3,17.7,19.4,19.1,17.8,17.5,91.0,90.0,91.0,162.0,3.2,1.4,NaN
4,2023/01/01,0400 UTC,0.0,887.6,887.9,887.6,NaN,19.7,18.1,19.7,19.1,18.1,17.4,91.0,90.0,90.0,140.0,5.7,2.7,NaN

In [5]:
hora23 = df2023["Hora UTC"].values
hora23 = [h.split(" ")[0][:2] + ":" + h.split(" ")[0][2:] for h in hora23]
df2023["Hora UTC"] = hora23
df2023.head()

,Data,Hora UTC,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2023/01/01,00:00,0.0,887.7,887.7,887.2,NaN,20.1,17.9,20.9,20.0,19.2,17.8,91.0,87.0,87.0,187.0,3.3,1.2,NaN
1,2023/01/01,01:00,0.0,888.1,888.1,887.7,NaN,19.2,17.5,20.1,19.2,17.8,17.4,90.0,87.0,90.0,153.0,2.9,0.8,NaN
2,2023/01/01,02:00,0.0,887.8,888.1,887.8,NaN,19.3,17.6,19.5,19.0,17.8,17.3,90.0,89.0,90.0,145.0,2.5,1.5,NaN
3,2023/01/01,03:00,0.0,887.8,887.9,887.7,NaN,19.3,17.7,19.4,19.1,17.8,17.5,91.0,90.0,91.0,162.0,3.2,1.4,NaN
4,2023/01/01,04:00,0.0,887.6,887.9,887.6,NaN,19.7,18.1,19.7,19.1,18.1,17.4,91.0,90.0,90.0,140.0,5.7,2.7,NaN

In [6]:

df2023.rename(columns={'Data':'DATA (YYYY-MM-DD)', 'Hora UTC':'HORA (UTC)', 'RADIACAO GLOBAL (Kj/m²)': 'RADIACAO GLOBAL (KJ/m²)'}, inplace=True)

In [7]:
df = pd.concat([df2003, df2013, df2023])
df

,DATA (YYYY-MM-DD),HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
0,2003-01-01,00:00,0.0,886.9,887.0,886.5,-9999.0,20.3,18.8,20.4,20.2,18.9,18.7,91.0,90.0,91.0,308.0,2.1,1.4,NaN
1,2003-01-01,01:00,0.0,887.3,887.3,886.9,-9999.0,19.9,18.5,20.3,19.9,18.8,18.5,92.0,91.0,92.0,302.0,2.2,1.3,NaN
2,2003-01-01,02:00,0.0,887.8,887.8,887.3,-9999.0,19.8,18.5,20.1,19.8,18.8,18.4,92.0,92.0,92.0,302.0,2.7,1.6,NaN
3,2003-01-01,03:00,0.0,886.9,887.8,886.9,-9999.0,19.5,18.5,19.8,19.5,18.6,18.4,94.0,92.0,94.0,295.0,3.4,2.0,NaN
4,2003-01-01,04:00,0.0,886.8,886.9,886.7,-9999.0,19.2,18.0,19.5,19.2,18.5,18.0,94.0,93.0,93.0,313.0,3.9,2.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2023/12/31,19:00,0.0,884.2,885.2,884.2,1252.2,26.1,18.4,28.1,26.0,19.0,16.9,64.0,52.0,63.0,1.0,5.3,2.1,NaN
8756,2023/12/31,20:00,0.0,883.7,884.3,883.7,1178.8,27.7,18.1,27.7,25.8,18.2,16.9,62.0,53.0,56.0,314.0,5.2,1.9,NaN
8757,2023/12/31,21:00,0.0,883.5,883.7,883.4,873.0,25.5,17.4,27.7,25.5,18.0,16.9,62.0,52.0,61.0,300.0,5.1,2.7,NaN
8758,2023/12/31,22:00,0.0,884.5,884.5,883.5,104.0,23.4,18.2,25.5,23.4,18.2,17.4,72.0,61.0,72.0,293.0,4.8,2.0,NaN
8759,2023/12/31,23:00,0.0,885.3,885.3,884.5,NaN,22.6,18.6,23.4,22.3,18.6,18.3,79.0,73.0,78.0,285.0,3.7,1.4,NaN

In [8]:
data = df["DATA (YYYY-MM-DD)"].values
index = pd.DatetimeIndex(data, name="Data")
df.drop("DATA (YYYY-MM-DD)", axis=1, inplace=True)
df.set_index(index, inplace=True)
df

,HORA (UTC),"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (KJ/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",Unnamed: 19
Data,,,,,,,,,,,,,,,,,,,
2003-01-01,00:00,0.0,886.9,887.0,886.5,-9999.0,20.3,18.8,20.4,20.2,18.9,18.7,91.0,90.0,91.0,308.0,2.1,1.4,NaN
2003-01-01,01:00,0.0,887.3,887.3,886.9,-9999.0,19.9,18.5,20.3,19.9,18.8,18.5,92.0,91.0,92.0,302.0,2.2,1.3,NaN
2003-01-01,02:00,0.0,887.8,887.8,887.3,-9999.0,19.8,18.5,20.1,19.8,18.8,18.4,92.0,92.0,92.0,302.0,2.7,1.6,NaN
2003-01-01,03:00,0.0,886.9,887.8,886.9,-9999.0,19.5,18.5,19.8,19.5,18.6,18.4,94.0,92.0,94.0,295.0,3.4,2.0,NaN
2003-01-01,04:00,0.0,886.8,886.9,886.7,-9999.0,19.2,18.0,19.5,19.2,18.5,18.0,94.0,93.0,93.0,313.0,3.9,2.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-31,19:00,0.0,884.2,885.2,884.2,1252.2,26.1,18.4,28.1,26.0,19.0,16.9,64.0,52.0,63.0,1.0,5.3,2.1,NaN
2023-12-31,20:00,0.0,883.7,884.3,883.7,1178.8,27.7,18.1,27.7,25.8,18.2,16.9,62.0,53.0,56.0,314.0,5.2,1.9,NaN
2023-12-31,21:00,0.0,883.5,883.7,883.4,873.0,25.5,17.4,27.7,25.5,18.0,16.9,62.0,52.0,61.0,300.0,5.1,2.7,NaN
2023-12-31,22:00,0.0,884.5,884.5,883.5,104.0,23.4,18.2,25.5,23.4,18.2,17.4,72.0,61.0,72.0,293.0,4.8,2.0,NaN
2023-12-31,23:00,0.0,885.3,885.3,884.5,NaN,22.6,18.6,23.4,22.3,18.6,18.3,79.0,73.0,78.0,285.0,3.7,1.4,NaN

In [9]:
mi = []
for columns in df.columns:
    a = (columns,"")
    if(columns.find("PRESSAO")>-1 or columns.find("PRESSÃO")>-1):
        a = ("Pressão",columns)
    if(columns.find("TEMPERATURA")>-1):
        a = ("Temperatura",columns)
    if(columns.find("UMIDADE")>-1):
        a = ("Umidade",columns)
    if(columns.find("VENTO")>-1):
        a = ("Velocidade do Vento",columns)
    mi.append(a)

In [10]:
df.columns = pd.MultiIndex.from_tuples(mi)
df

           HORA (UTC) PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \

Data
2003-01-01      00:00                              0.0
2003-01-01      01:00                              0.0
2003-01-01      02:00                              0.0
2003-01-01      03:00                              0.0
2003-01-01      04:00                              0.0
...               ...                              ...
2023-12-31      19:00                              0.0
2023-12-31      20:00                              0.0
2023-12-31      21:00                              0.0
2023-12-31      22:00                              0.0
2023-12-31      23:00                              0.0

                                                         Pressão  \
           PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
Data
2003-01-01                                              886.9
2003-01-01                                              887.3
2003-01-01                                              887.8
2003-01-01                                              886.9
2003-01-01                                              886.8
...                                                       ...
2023-12-31                                              884.2
2023-12-31                                              883.7
2023-12-31                                              883.5
2023-12-31                                              884.5
2023-12-31                                              885.3

                                                            \
           PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
Data
2003-01-01                                           887.0
2003-01-01                                           887.3
2003-01-01                                           887.8
2003-01-01                                           887.8
2003-01-01                                           886.9
...                                                    ...
2023-12-31                                           885.2
2023-12-31                                           884.3
2023-12-31                                           883.7
2023-12-31                                           884.5
2023-12-31                                           885.3

                                                             \
           PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
Data
2003-01-01                                            886.5
2003-01-01                                            886.9
2003-01-01                                            887.3
2003-01-01                                            886.9
2003-01-01                                            886.7
...                                                     ...
2023-12-31                                            884.2
2023-12-31                                            883.7
2023-12-31                                            883.4
2023-12-31                                            883.5
2023-12-31                                            884.5

           RADIACAO GLOBAL (KJ/m²)  \

Data
2003-01-01                 -9999.0
2003-01-01                 -9999.0
2003-01-01                 -9999.0
2003-01-01                 -9999.0
2003-01-01                 -9999.0
...                            ...
2023-12-31                  1252.2
2023-12-31                  1178.8
2023-12-31                   873.0
2023-12-31                   104.0
2023-12-31                     NaN

                                            Temperatura  \
           TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
Data
2003-01-01                                         20.3
2003-01-01                                         19.9
2003-01-01                                         19.8
2003-01-01                                         19.5
2003-01-01                                         19.2
...                                                 ...
2023-12-31                                         26.1
2023-12-31                                         27.7
2023-12-31                                         25.5
2023-12-31                                         23.4
2023-12-31                                         22.6

                                                 \
           TEMPERATURA DO PONTO DE ORVALHO (°C)
Data
2003-01-01                                 18.8
2003-01-01                                 18.5
2003-01-01                                 18.5
2003-01-01                                 18.5
2003-01-01                                 18.0
...                                         ...
2023-12-31                                 18.4
2023-12-31                                 18.1
2023-12-31                                 17.4
2023-12-31                                 18.2
2023-12-31                                 18.6

                                                       \
           TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
Data
2003-01-01                                       20.4
2003-01-01                                       20.3
2003-01-01                                       20.1
2003-01-01                                       19.8
2003-01-01                                       19.5
...                                               ...
2023-12-31                                       28.1
2023-12-31                                       27.7
2023-12-31                                       27.7
2023-12-31                                       25.5
2023-12-31                                       23.4

                                                       \
           TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
Data
2003-01-01                                       20.2
2003-01-01                                       19.9
2003-01-01                                       19.8
2003-01-01                                       19.5
2003-01-01                                       19.2
...                                               ...
2023-12-31                                       26.0
2023-12-31                                       25.8
2023-12-31                                       25.5
2023-12-31                                       23.4
2023-12-31                                       22.3

                                                             \
           TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
Data
2003-01-01                                             18.9
2003-01-01                                             18.8
2003-01-01                                             18.8
2003-01-01                                             18.6
2003-01-01                                             18.5
...                                                     ...
2023-12-31                                             19.0
2023-12-31                                             18.2
2023-12-31                                             18.0
2023-12-31                                             18.2
2023-12-31                                             18.6

                                                             \
           TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
Data
2003-01-01                                             18.7
2003-01-01                                             18.5
2003-01-01                                             18.4
2003-01-01                                             18.4
2003-01-01                                             18.0
...                                                     ...
2023-12-31                                             16.9
2023-12-31                                             16.9
2023-12-31                                             16.9
2023-12-31                                             17.4
2023-12-31                                             18.3

                                            Umidade  \
           UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
Data
2003-01-01                                     91.0
2003-01-01                                     92.0
2003-01-01                                     92.0
2003-01-01                                     94.0
2003-01-01                                     94.0
...                                             ...
2023-12-31                                     64.0
2023-12-31                                     62.0
2023-12-31                                     62.0
2023-12-31                                     72.0
2023-12-31                                     79.0

                                                     \
           UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
Data
2003-01-01                                     90.0
2003-01-01                                     91.0
2003-01-01                                     92.0
2003-01-01                                     92.0
2003-01-01                                     93.0
...                                             ...
2023-12-31                                     52.0
2023-12-31                                     53.0
2023-12-31                                     52.0
2023-12-31                                     61.0
2023-12-31                                     73.0

                                                \
           UMIDADE RELATIVA DO AR, HORARIA (%)
Data
2003-01-01                                91.0
2003-01-01                                92.0
2003-01-01                                92.0
2003-01-01                                94.0
2003-01-01                                93.0
...                                        ...
2023-12-31                                63.0
2023-12-31                                56.0
2023-12-31                                61.0
2023-12-31                                72.0
2023-12-31                                78.0

                            Velocidade do Vento                             \
           VENTO, DIREÇÃO HORARIA (gr) (° (gr)) VENTO, RAJADA MAXIMA (m/s)
Data
2003-01-01                                308.0                        2.1
2003-01-01                                302.0                        2.2
2003-01-01                                302.0                        2.7
2003-01-01                                295.0                        3.4
2003-01-01                                313.0                        3.9
...                                         ...                        ...
2023-12-31                                  1.0                        5.3
2023-12-31                                314.0                        5.2
2023-12-31                                300.0                        5.1
2023-12-31                                293.0                        4.8
2023-12-31                                285.0                        3.7

                                           Unnamed: 19
           VENTO, VELOCIDADE HORARIA (m/s)
Data
2003-01-01                             1.4         NaN
2003-01-01                             1.3         NaN
2003-01-01                             1.6         NaN
2003-01-01                             2.0         NaN
2003-01-01                             2.5         NaN
...                                    ...         ...
2023-12-31                             2.1         NaN
2023-12-31                             1.9         NaN
2023-12-31                             2.7         NaN
2023-12-31                             2.0         NaN
2023-12-31                             1.4         NaN

[26280 rows x 19 columns]

In [11]:
df.groupby(df.index.year)["PRECIPITAÇÃO TOTAL, HORÁRIO (mm)"].agg(["mean", "min", "max"])

            mean     min   max
Data
2003 -590.010502 -9999.0  33.4
2013  -23.788082 -9999.0  40.2
2023    0.113764     0.0  23.4

In [12]:
df.groupby(df.index.year)["Temperatura"].agg(["mean", "min", "max"])

                                      Temperatura                \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
                                             mean     min   max
Data
2003                                  -570.075000 -9999.0  33.0
2013                                    -1.617511 -9999.0  32.6
2023                                    21.955477     9.6  34.4

                                                         \
     TEMPERATURA DO PONTO DE ORVALHO (°C)
                                     mean     min   max
Data
2003                          -577.182169 -9999.0  20.1
2013                            -8.624635 -9999.0  20.5
2023                            14.184500    -1.1  21.5

                                                               \
     TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
                                           mean     min   max
Data
2003                                -609.560856 -9999.0  33.2
2013                                  -0.921632 -9999.0  32.7
2023                                  22.735544    10.7  34.6

                                                               \
     TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
                                           mean     min   max
Data
2003                                -610.650297 -9999.0  32.4
2013                                  -2.265799 -9999.0  31.5
2023                                  21.207454     9.4  33.0

                                                                     \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
                                                 mean     min   max
Data
2003                                      -616.726153 -9999.0  20.8
2013                                        -8.039772 -9999.0  21.3
2023                                        14.816086     0.0  22.3


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
                                                 mean     min   max
Data
2003                                      -617.654007 -9999.0  19.6
2013                                        -9.173721 -9999.0  19.9
2023                                        13.605751    -1.4  21.3

In [13]:
ndf = df.loc[df.index.month == 1]
ndf.groupby(ndf.index.year)["PRECIPITAÇÃO TOTAL, HORÁRIO (mm)"].agg(["mean", "min", "max"])

            mean     min   max
Data
2003 -362.601344 -9999.0  14.2
2013    0.608602     0.0  40.2
2023    0.256452     0.0  17.6

In [14]:
ndf.groupby(ndf.index.year)["Temperatura"].agg(["mean", "min", "max"])

                                      Temperatura                \
     TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
                                             mean     min   max
Data
2003                                  -341.878226 -9999.0  29.1
2013                                    21.148522    15.6  29.9
2023                                    21.033602    15.8  28.2

                                                         \
     TEMPERATURA DO PONTO DE ORVALHO (°C)
                                     mean     min   max
Data
2003                          -345.802823 -9999.0  20.1
2013                            17.193952     8.5  20.5
2023                            16.839113    11.9  19.6

                                                               \
     TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
                                           mean     min   max
Data
2003                                -381.752151 -9999.0  30.0
2013                                  21.710349    15.9  30.6
2023                                  21.704167    16.1  28.9

                                                               \
     TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
                                           mean     min   max
Data
2003                                -382.804032 -9999.0  28.8
2013                                  20.635887    15.6  29.2
2023                                  20.410618    15.6  27.2

                                                                     \
     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
                                                 mean     min   max
Data
2003                                      -385.720968 -9999.0  20.8
2013                                        17.728226    10.0  20.8
2023                                        17.418414    13.3  20.1


     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
                                                 mean     min   max
Data
2003                                      -386.655376 -9999.0  19.6
2013                                        16.666398     5.8  19.8
2023                                        16.297849    11.2  18.7

In [15]:
estacao = ["Verâo" if (1 <= x  <= 3) else x for x in df.index.month]
estacao = ["Outono" if type(x) != str and (4 <= x  <= 6) else x for x in estacao]
estacao = ["Inverno" if type(x) != str and (7 <= x  <= 9) else x for x in estacao]
estacao = ["Primavera" if type(x) != str and (10 <= x  <= 12) else x for x in estacao]

In [16]:
tuplas = list(zip(index, estacao))
multiindex = pd.MultiIndex.from_tuples(tuplas, names=['Data', 'Estação'])
df.set_index(multiindex, inplace=True)
df

                     HORA (UTC) PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \

Data       Estação
2003-01-01 Verâo          00:00                              0.0
           Verâo          01:00                              0.0
           Verâo          02:00                              0.0
           Verâo          03:00                              0.0
           Verâo          04:00                              0.0
...                         ...                              ...
2023-12-31 Primavera      19:00                              0.0
           Primavera      20:00                              0.0
           Primavera      21:00                              0.0
           Primavera      22:00                              0.0
           Primavera      23:00                              0.0

                                                                   Pressão  \
                     PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
Data       Estação
2003-01-01 Verâo                                                  886.9
           Verâo                                                  887.3
           Verâo                                                  887.8
           Verâo                                                  886.9
           Verâo                                                  886.8
...                                                                 ...
2023-12-31 Primavera                                              884.2
           Primavera                                              883.7
           Primavera                                              883.5
           Primavera                                              884.5
           Primavera                                              885.3

                                                                      \
                     PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
Data       Estação
2003-01-01 Verâo                                               887.0
           Verâo                                               887.3
           Verâo                                               887.8
           Verâo                                               887.8
           Verâo                                               886.9
...                                                              ...
2023-12-31 Primavera                                           885.2
           Primavera                                           884.3
           Primavera                                           883.7
           Primavera                                           884.5
           Primavera                                           885.3

                                                                       \
                     PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
Data       Estação
2003-01-01 Verâo                                                886.5
           Verâo                                                886.9
           Verâo                                                887.3
           Verâo                                                886.9
           Verâo                                                886.7
...                                                               ...
2023-12-31 Primavera                                            884.2
           Primavera                                            883.7
           Primavera                                            883.4
           Primavera                                            883.5
           Primavera                                            884.5

                     RADIACAO GLOBAL (KJ/m²)  \

Data       Estação
2003-01-01 Verâo                     -9999.0
           Verâo                     -9999.0
           Verâo                     -9999.0
           Verâo                     -9999.0
           Verâo                     -9999.0
...                                      ...
2023-12-31 Primavera                  1252.2
           Primavera                  1178.8
           Primavera                   873.0
           Primavera                   104.0
           Primavera                     NaN

                                                      Temperatura  \
                     TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
Data       Estação
2003-01-01 Verâo                                             20.3
           Verâo                                             19.9
           Verâo                                             19.8
           Verâo                                             19.5
           Verâo                                             19.2
...                                                           ...
2023-12-31 Primavera                                         26.1
           Primavera                                         27.7
           Primavera                                         25.5
           Primavera                                         23.4
           Primavera                                         22.6

                                                           \
                     TEMPERATURA DO PONTO DE ORVALHO (°C)
Data       Estação
2003-01-01 Verâo                                     18.8
           Verâo                                     18.5
           Verâo                                     18.5
           Verâo                                     18.5
           Verâo                                     18.0
...                                                   ...
2023-12-31 Primavera                                 18.4
           Primavera                                 18.1
           Primavera                                 17.4
           Primavera                                 18.2
           Primavera                                 18.6

                                                                 \
                     TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
Data       Estação
2003-01-01 Verâo                                           20.4
           Verâo                                           20.3
           Verâo                                           20.1
           Verâo                                           19.8
           Verâo                                           19.5
...                                                         ...
2023-12-31 Primavera                                       28.1
           Primavera                                       27.7
           Primavera                                       27.7
           Primavera                                       25.5
           Primavera                                       23.4

                                                                 \
                     TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
Data       Estação
2003-01-01 Verâo                                           20.2
           Verâo                                           19.9
           Verâo                                           19.8
           Verâo                                           19.5
           Verâo                                           19.2
...                                                         ...
2023-12-31 Primavera                                       26.0
           Primavera                                       25.8
           Primavera                                       25.5
           Primavera                                       23.4
           Primavera                                       22.3

                                                                       \
                     TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
Data       Estação
2003-01-01 Verâo                                                 18.9
           Verâo                                                 18.8
           Verâo                                                 18.8
           Verâo                                                 18.6
           Verâo                                                 18.5
...                                                               ...
2023-12-31 Primavera                                             19.0
           Primavera                                             18.2
           Primavera                                             18.0
           Primavera                                             18.2
           Primavera                                             18.6

                                                                       \
                     TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
Data       Estação
2003-01-01 Verâo                                                 18.7
           Verâo                                                 18.5
           Verâo                                                 18.4
           Verâo                                                 18.4
           Verâo                                                 18.0
...                                                               ...
2023-12-31 Primavera                                             16.9
           Primavera                                             16.9
           Primavera                                             16.9
           Primavera                                             17.4
           Primavera                                             18.3

                                                      Umidade  \
                     UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
Data       Estação
2003-01-01 Verâo                                         91.0
           Verâo                                         92.0
           Verâo                                         92.0
           Verâo                                         94.0
           Verâo                                         94.0
...                                                       ...
2023-12-31 Primavera                                     64.0
           Primavera                                     62.0
           Primavera                                     62.0
           Primavera                                     72.0
           Primavera                                     79.0

                                                               \
                     UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
Data       Estação
2003-01-01 Verâo                                         90.0
           Verâo                                         91.0
           Verâo                                         92.0
           Verâo                                         92.0
           Verâo                                         93.0
...                                                       ...
2023-12-31 Primavera                                     52.0
           Primavera                                     53.0
           Primavera                                     52.0
           Primavera                                     61.0
           Primavera                                     73.0

                                                          \
                     UMIDADE RELATIVA DO AR, HORARIA (%)
Data       Estação
2003-01-01 Verâo                                    91.0
           Verâo                                    92.0
           Verâo                                    92.0
           Verâo                                    94.0
           Verâo                                    93.0
...                                                  ...
2023-12-31 Primavera                                63.0
           Primavera                                56.0
           Primavera                                61.0
           Primavera                                72.0
           Primavera                                78.0

                                      Velocidade do Vento  \
                     VENTO, DIREÇÃO HORARIA (gr) (° (gr))
Data       Estação
2003-01-01 Verâo                                    308.0
           Verâo                                    302.0
           Verâo                                    302.0
           Verâo                                    295.0
           Verâo                                    313.0
...                                                   ...
2023-12-31 Primavera                                  1.0
           Primavera                                314.0
           Primavera                                300.0
           Primavera                                293.0
           Primavera                                285.0

                                                 \
                     VENTO, RAJADA MAXIMA (m/s)
Data       Estação
2003-01-01 Verâo                            2.1
           Verâo                            2.2
           Verâo                            2.7
           Verâo                            3.4
           Verâo                            3.9
...                                         ...
2023-12-31 Primavera                        5.3
           Primavera                        5.2
           Primavera                        5.1
           Primavera                        4.8
           Primavera                        3.7

                                                     Unnamed: 19
                     VENTO, VELOCIDADE HORARIA (m/s)
Data       Estação
2003-01-01 Verâo                                 1.4         NaN
           Verâo                                 1.3         NaN
           Verâo                                 1.6         NaN
           Verâo                                 2.0         NaN
           Verâo                                 2.5         NaN
...                                              ...         ...
2023-12-31 Primavera                             2.1         NaN
           Primavera                             1.9         NaN
           Primavera                             2.7         NaN
           Primavera                             2.0         NaN
           Primavera                             1.4         NaN

[26280 rows x 19 columns]

In [17]:
ano = df.index.get_level_values("Data").year

In [18]:
df.groupby([ano, "Estação"])["PRECIPITAÇÃO TOTAL, HORÁRIO (mm)"].agg(["mean", "min", "max"])

                      mean     min   max
Data Estação
2003 Inverno   -584.159873 -9999.0   7.6
     Outono    -650.079762 -9999.0  24.8
     Primavera -285.107971 -9999.0  33.4
     Verâo     -846.932593 -9999.0  29.4
2013 Inverno      0.026540     0.0  24.8
     Outono      -9.103480 -9999.0  11.2
     Primavera   -4.237591 -9999.0  30.8
     Verâo      -82.964630 -9999.0  40.2
2023 Inverno      0.030644     0.0  16.6
     Outono       0.087546     0.0  23.4
     Primavera    0.161542     0.0  21.4
     Verâo        0.176389     0.0  18.2

In [19]:
df.groupby([ano, "Estação"])["Temperatura"].agg(["mean", "min", "max"])

                                                Temperatura                \
               TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
                                                       mean     min   max
Data Estação
2003 Inverno                                    -564.520018 -9999.0  33.0
     Outono                                     -630.989789 -9999.0  28.8
     Primavera                                  -263.724774 -9999.0  32.7
     Verâo                                      -827.319815 -9999.0  29.1
2013 Inverno                                      21.005933    11.0  32.6
     Outono                                       11.288645 -9999.0  28.1
     Primavera                                    21.598958    14.3  31.0
     Verâo                                       -61.525648 -9999.0  30.2
2023 Inverno                                      21.921034     9.6  33.5
     Outono                                       20.101877    10.3  29.0
     Primavera                                    24.031927    16.5  34.4
     Verâo                                        21.745139    14.9  30.4

                                                                   \
               TEMPERATURA DO PONTO DE ORVALHO (°C)
                                               mean     min   max
Data Estação
2003 Inverno                            -574.933243 -9999.0  17.4
     Outono                             -637.854075 -9999.0  19.5
     Primavera                          -270.725543 -9999.0  19.6
     Verâo                              -831.401806 -9999.0  20.1
2013 Inverno                               9.566033    -1.6  19.0
     Outono                                5.290614 -9999.0  20.4
     Primavera                            16.082971     6.5  20.4
     Verâo                               -66.546065 -9999.0  20.5
2023 Inverno                              10.382366    -1.1  19.3
     Outono                               13.680128     5.2  20.4
     Primavera                            16.246304     5.3  21.5
     Verâo                                16.472824    10.4  19.7

                                                                         \
               TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
                                                     mean     min   max
Data Estação
2003 Inverno                                  -600.226585 -9999.0  33.2
     Outono                                   -676.317353 -9999.0  29.6
     Primavera                                -285.867889 -9999.0  33.1
     Verâo                                    -882.490463 -9999.0  30.0
2013 Inverno                                    21.820335    11.8  32.7
     Outono                                     11.958700 -9999.0  28.8
     Primavera                                  22.247600    14.4  31.9
     Verâo                                     -60.876528 -9999.0  31.1
2023 Inverno                                    22.792364    10.7  34.2
     Outono                                     20.872161    10.7  29.8
     Primavera                                  24.813845    17.2  34.6
     Verâo                                      22.442083    15.4  30.9

                                                                         \
               TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
                                                     mean     min   max
Data Estação
2003 Inverno                                  -601.396196 -9999.0  32.4
     Outono                                   -677.431685 -9999.0  28.1
     Primavera                                -286.938315 -9999.0  32.2
     Verâo                                    -883.492222 -9999.0  28.8
2013 Inverno                                    20.240942    10.6  31.5
     Outono                                     10.659158 -9999.0  27.0
     Primavera                                  20.996422    14.1  29.7
     Verâo                                     -62.120417 -9999.0  29.2
2023 Inverno                                    21.087000     9.4  32.5
     Outono                                     19.365064    10.1  27.8
     Primavera                                  23.273128    15.8  33.0
     Verâo                                      21.086204    14.3  29.7

                                                                               \
               TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
                                                           mean     min   max
Data Estação
2003 Inverno                                        -610.773596 -9999.0  18.0
     Outono                                         -683.273718 -9999.0  19.9
     Primavera                                      -292.852717 -9999.0  20.7
     Verâo                                          -886.594630 -9999.0  20.8
2013 Inverno                                          10.100362    -0.4  19.6
     Outono                                            5.841804 -9999.0  21.0
     Primavera                                        16.719203     7.2  21.3
     Verâo                                           -65.928009 -9999.0  21.3
2023 Inverno                                          10.979682     0.0  19.5
     Outono                                           14.249679     7.2  20.9
     Primavera                                        16.980890     6.0  22.3
     Verâo                                            17.088333    11.7  20.1


               TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
                                                           mean     min   max
Data Estação
2003 Inverno                                        -611.646286 -9999.0  16.5
     Outono                                         -684.117674 -9999.0  19.1
     Primavera                                      -293.937681 -9999.0  19.0
     Verâo                                          -887.503102 -9999.0  19.6
2013 Inverno                                           9.056748    -1.9  17.7
     Outono                                            4.789927 -9999.0  19.9
     Primavera                                        15.482201     5.2  19.8
     Verâo                                           -67.131944 -9999.0  19.8
2023 Inverno                                           9.838864    -1.4  19.3
     Outono                                           13.163645     4.0  19.4
     Primavera                                        15.567000     5.1  21.3
     Verâo                                            15.889120     8.3  18.9

In [21]:
hora = df["HORA (UTC)"].values
hora = [h[:2] for h in hora]

In [22]:

intervalo = ["Madrugada" if (0 <= int(x) < 6) else x for x in hora]
intervalo = ["Manhã" if (x[1]!= 'a') and (6 <= int(x) < 12) else x for x in intervalo]
intervalo = ["Tarde" if (x[1]!= 'a') and (12 <= int(x) < 18) else x for x in intervalo]
intervalo = ["Noite" if (x[1]!= 'a') and (18 <= int(x) < 24) else x for x in intervalo]

In [23]:
tuplas = list(zip(index, estacao, intervalo))
multiindex = pd.MultiIndex.from_tuples(tuplas, names=['Data', 'Estação', 'Intervalo'])
df.set_index(multiindex, inplace=True)
df

                               HORA (UTC) PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \

Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada      00:00                              0.0
                     Madrugada      01:00                              0.0
                     Madrugada      02:00                              0.0
                     Madrugada      03:00                              0.0
                     Madrugada      04:00                              0.0
...                                   ...                              ...
2023-12-31 Primavera Noite          19:00                              0.0
                     Noite          20:00                              0.0
                     Noite          21:00                              0.0
                     Noite          22:00                              0.0
                     Noite          23:00                              0.0

                                                                             Pressão  \
                               PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                              886.9
                     Madrugada                                              887.3
                     Madrugada                                              887.8
                     Madrugada                                              886.9
                     Madrugada                                              886.8
...                                                                           ...
2023-12-31 Primavera Noite                                                  884.2
                     Noite                                                  883.7
                     Noite                                                  883.5
                     Noite                                                  884.5
                     Noite                                                  885.3

                                                                                \
                               PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                           887.0
                     Madrugada                                           887.3
                     Madrugada                                           887.8
                     Madrugada                                           887.8
                     Madrugada                                           886.9
...                                                                        ...
2023-12-31 Primavera Noite                                               885.2
                     Noite                                               884.3
                     Noite                                               883.7
                     Noite                                               884.5
                     Noite                                               885.3

                                                                                 \
                               PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                            886.5
                     Madrugada                                            886.9
                     Madrugada                                            887.3
                     Madrugada                                            886.9
                     Madrugada                                            886.7
...                                                                         ...
2023-12-31 Primavera Noite                                                884.2
                     Noite                                                883.7
                     Noite                                                883.4
                     Noite                                                883.5
                     Noite                                                884.5

                               RADIACAO GLOBAL (KJ/m²)  \

Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                 -9999.0
                     Madrugada                 -9999.0
                     Madrugada                 -9999.0
                     Madrugada                 -9999.0
                     Madrugada                 -9999.0
...                                                ...
2023-12-31 Primavera Noite                      1252.2
                     Noite                      1178.8
                     Noite                       873.0
                     Noite                       104.0
                     Noite                         NaN

                                                                Temperatura  \
                               TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                         20.3
                     Madrugada                                         19.9
                     Madrugada                                         19.8
                     Madrugada                                         19.5
                     Madrugada                                         19.2
...                                                                     ...
2023-12-31 Primavera Noite                                             26.1
                     Noite                                             27.7
                     Noite                                             25.5
                     Noite                                             23.4
                     Noite                                             22.6

                                                                     \
                               TEMPERATURA DO PONTO DE ORVALHO (°C)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                 18.8
                     Madrugada                                 18.5
                     Madrugada                                 18.5
                     Madrugada                                 18.5
                     Madrugada                                 18.0
...                                                             ...
2023-12-31 Primavera Noite                                     18.4
                     Noite                                     18.1
                     Noite                                     17.4
                     Noite                                     18.2
                     Noite                                     18.6

                                                                           \
                               TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                       20.4
                     Madrugada                                       20.3
                     Madrugada                                       20.1
                     Madrugada                                       19.8
                     Madrugada                                       19.5
...                                                                   ...
2023-12-31 Primavera Noite                                           28.1
                     Noite                                           27.7
                     Noite                                           27.7
                     Noite                                           25.5
                     Noite                                           23.4

                                                                           \
                               TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                       20.2
                     Madrugada                                       19.9
                     Madrugada                                       19.8
                     Madrugada                                       19.5
                     Madrugada                                       19.2
...                                                                   ...
2023-12-31 Primavera Noite                                           26.0
                     Noite                                           25.8
                     Noite                                           25.5
                     Noite                                           23.4
                     Noite                                           22.3

                                                                                 \
                               TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                             18.9
                     Madrugada                                             18.8
                     Madrugada                                             18.8
                     Madrugada                                             18.6
                     Madrugada                                             18.5
...                                                                         ...
2023-12-31 Primavera Noite                                                 19.0
                     Noite                                                 18.2
                     Noite                                                 18.0
                     Noite                                                 18.2
                     Noite                                                 18.6

                                                                                 \
                               TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                             18.7
                     Madrugada                                             18.5
                     Madrugada                                             18.4
                     Madrugada                                             18.4
                     Madrugada                                             18.0
...                                                                         ...
2023-12-31 Primavera Noite                                                 16.9
                     Noite                                                 16.9
                     Noite                                                 16.9
                     Noite                                                 17.4
                     Noite                                                 18.3

                                                                Umidade  \
                               UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                     91.0
                     Madrugada                                     92.0
                     Madrugada                                     92.0
                     Madrugada                                     94.0
                     Madrugada                                     94.0
...                                                                 ...
2023-12-31 Primavera Noite                                         64.0
                     Noite                                         62.0
                     Noite                                         62.0
                     Noite                                         72.0
                     Noite                                         79.0

                                                                         \
                               UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                     90.0
                     Madrugada                                     91.0
                     Madrugada                                     92.0
                     Madrugada                                     92.0
                     Madrugada                                     93.0
...                                                                 ...
2023-12-31 Primavera Noite                                         52.0
                     Noite                                         53.0
                     Noite                                         52.0
                     Noite                                         61.0
                     Noite                                         73.0

                                                                    \
                               UMIDADE RELATIVA DO AR, HORARIA (%)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                91.0
                     Madrugada                                92.0
                     Madrugada                                92.0
                     Madrugada                                94.0
                     Madrugada                                93.0
...                                                            ...
2023-12-31 Primavera Noite                                    63.0
                     Noite                                    56.0
                     Noite                                    61.0
                     Noite                                    72.0
                     Noite                                    78.0

                                                Velocidade do Vento  \
                               VENTO, DIREÇÃO HORARIA (gr) (° (gr))
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                                308.0
                     Madrugada                                302.0
                     Madrugada                                302.0
                     Madrugada                                295.0
                     Madrugada                                313.0
...                                                             ...
2023-12-31 Primavera Noite                                      1.0
                     Noite                                    314.0
                     Noite                                    300.0
                     Noite                                    293.0
                     Noite                                    285.0

                                                           \
                               VENTO, RAJADA MAXIMA (m/s)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                        2.1
                     Madrugada                        2.2
                     Madrugada                        2.7
                     Madrugada                        3.4
                     Madrugada                        3.9
...                                                   ...
2023-12-31 Primavera Noite                            5.3
                     Noite                            5.2
                     Noite                            5.1
                     Noite                            4.8
                     Noite                            3.7

                                                               Unnamed: 19
                               VENTO, VELOCIDADE HORARIA (m/s)
Data       Estação   Intervalo
2003-01-01 Verâo     Madrugada                             1.4         NaN
                     Madrugada                             1.3         NaN
                     Madrugada                             1.6         NaN
                     Madrugada                             2.0         NaN
                     Madrugada                             2.5         NaN
...                                                        ...         ...
2023-12-31 Primavera Noite                                 2.1         NaN
                     Noite                                 1.9         NaN
                     Noite                                 2.7         NaN
                     Noite                                 2.0         NaN
                     Noite                                 1.4         NaN

[26280 rows x 19 columns]

In [24]:
idf = df.loc[df.index.get_level_values("Data").month == 9]
idf = idf.loc[idf.index.get_level_values("Data").day == 28]
idf

                             HORA (UTC) PRECIPITAÇÃO TOTAL, HORÁRIO (mm)  \

Data       Estação Intervalo
2003-09-28 Inverno Madrugada      00:00                              0.0
                   Madrugada      01:00                              0.0
                   Madrugada      02:00                              0.0
                   Madrugada      03:00                              0.0
                   Madrugada      04:00                              0.0
...                                 ...                              ...
2023-09-28 Inverno Noite          19:00                              0.0
                   Noite          20:00                              0.0
                   Noite          21:00                              0.0
                   Noite          22:00                              0.0
                   Noite          23:00                              0.0

                                                                           Pressão  \
                             PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                              884.5
                   Madrugada                                              885.1
                   Madrugada                                              885.2
                   Madrugada                                              885.0
                   Madrugada                                              884.5
...                                                                         ...
2023-09-28 Inverno Noite                                                  883.5
                   Noite                                                  883.6
                   Noite                                                  883.6
                   Noite                                                  884.9
                   Noite                                                  885.8

                                                                              \
                             PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                           884.5
                   Madrugada                                           885.1
                   Madrugada                                           885.4
                   Madrugada                                           885.3
                   Madrugada                                           885.0
...                                                                      ...
2023-09-28 Inverno Noite                                               883.8
                   Noite                                               883.9
                   Noite                                               883.8
                   Noite                                               884.9
                   Noite                                               885.8

                                                                               \
                             PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                            884.3
                   Madrugada                                            884.6
                   Madrugada                                            885.1
                   Madrugada                                            885.0
                   Madrugada                                            884.5
...                                                                       ...
2023-09-28 Inverno Noite                                                883.3
                   Noite                                                883.5
                   Noite                                                883.5
                   Noite                                                883.6
                   Noite                                                884.8

                             RADIACAO GLOBAL (KJ/m²)  \

Data       Estação Intervalo
2003-09-28 Inverno Madrugada                 -9999.0
                   Madrugada                 -9999.0
                   Madrugada                 -9999.0
                   Madrugada                 -9999.0
                   Madrugada                 -9999.0
...                                              ...
2023-09-28 Inverno Noite                       459.7
                   Noite                       257.8
                   Noite                       154.4
                   Noite                         0.6
                   Noite                         NaN

                                                              Temperatura  \
                             TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                         21.6
                   Madrugada                                         21.5
                   Madrugada                                         21.5
                   Madrugada                                         20.8
                   Madrugada                                         20.9
...                                                                   ...
2023-09-28 Inverno Noite                                             25.2
                   Noite                                             26.0
                   Noite                                             25.9
                   Noite                                             25.1
                   Noite                                             24.3

                                                                   \
                             TEMPERATURA DO PONTO DE ORVALHO (°C)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                 13.0
                   Madrugada                                 14.5
                   Madrugada                                 14.2
                   Madrugada                                 14.3
                   Madrugada                                 14.8
...                                                           ...
2023-09-28 Inverno Noite                                     15.1
                   Noite                                     15.2
                   Noite                                     14.7
                   Noite                                     14.8
                   Noite                                     15.2

                                                                         \
                             TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                       22.4
                   Madrugada                                       22.0
                   Madrugada                                       21.5
                   Madrugada                                       22.0
                   Madrugada                                       21.1
...                                                                 ...
2023-09-28 Inverno Noite                                           32.4
                   Noite                                           26.0
                   Noite                                           26.3
                   Noite                                           26.4
                   Noite                                           25.2

                                                                         \
                             TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                       21.6
                   Madrugada                                       21.1
                   Madrugada                                       21.0
                   Madrugada                                       20.8
                   Madrugada                                       20.8
...                                                                 ...
2023-09-28 Inverno Noite                                           25.2
                   Noite                                           25.1
                   Noite                                           25.9
                   Noite                                           24.9
                   Noite                                           24.0

                                                                               \
                             TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                             13.7
                   Madrugada                                             14.5
                   Madrugada                                             14.9
                   Madrugada                                             14.7
                   Madrugada                                             15.1
...                                                                       ...
2023-09-28 Inverno Noite                                                 15.7
                   Noite                                                 15.7
                   Noite                                                 15.2
                   Noite                                                 15.7
                   Noite                                                 15.2

                                                                               \
                             TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                             12.6
                   Madrugada                                             12.9
                   Madrugada                                             14.2
                   Madrugada                                             13.9
                   Madrugada                                             14.3
...                                                                       ...
2023-09-28 Inverno Noite                                                 13.4
                   Noite                                                 15.0
                   Noite                                                 14.1
                   Noite                                                 13.8
                   Noite                                                 14.4

                                                              Umidade  \
                             UMIDADE REL. MAX. NA HORA ANT. (AUT) (%)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                     59.0
                   Madrugada                                     64.0
                   Madrugada                                     67.0
                   Madrugada                                     68.0
                   Madrugada                                     69.0
...                                                               ...
2023-09-28 Inverno Noite                                         55.0
                   Noite                                         55.0
                   Noite                                         51.0
                   Noite                                         56.0
                   Noite                                         58.0

                                                                       \
                             UMIDADE REL. MIN. NA HORA ANT. (AUT) (%)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                     54.0
                   Madrugada                                     58.0
                   Madrugada                                     63.0
                   Madrugada                                     60.0
                   Madrugada                                     66.0
...                                                               ...
2023-09-28 Inverno Noite                                         35.0
                   Noite                                         51.0
                   Noite                                         48.0
                   Noite                                         46.0
                   Noite                                         51.0

                                                                  \
                             UMIDADE RELATIVA DO AR, HORARIA (%)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                58.0
                   Madrugada                                64.0
                   Madrugada                                63.0
                   Madrugada                                67.0
                   Madrugada                                68.0
...                                                          ...
2023-09-28 Inverno Noite                                    54.0
                   Noite                                    51.0
                   Noite                                    50.0
                   Noite                                    53.0
                   Noite                                    57.0

                                              Velocidade do Vento  \
                             VENTO, DIREÇÃO HORARIA (gr) (° (gr))
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                                170.0
                   Madrugada                                304.0
                   Madrugada                                232.0
                   Madrugada                                358.0
                   Madrugada                                343.0
...                                                           ...
2023-09-28 Inverno Noite                                    328.0
                   Noite                                    300.0
                   Noite                                    156.0
                   Noite                                      6.0
                   Noite                                    292.0

                                                         \
                             VENTO, RAJADA MAXIMA (m/s)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                        2.5
                   Madrugada                        2.2
                   Madrugada                        2.5
                   Madrugada                        1.9
                   Madrugada                        1.5
...                                                 ...
2023-09-28 Inverno Noite                            8.4
                   Noite                            4.8
                   Noite                            2.9
                   Noite                            5.4
                   Noite                            4.4

                                                             Unnamed: 19
                             VENTO, VELOCIDADE HORARIA (m/s)
Data       Estação Intervalo
2003-09-28 Inverno Madrugada                             0.8         NaN
                   Madrugada                             1.2         NaN
                   Madrugada                             1.8         NaN
                   Madrugada                             0.5         NaN
                   Madrugada                             0.9         NaN
...                                                      ...         ...
2023-09-28 Inverno Noite                                 2.3         NaN
                   Noite                                 1.3         NaN
                   Noite                                 0.5         NaN
                   Noite                                 1.7         NaN
                   Noite                                 1.5         NaN

[72 rows x 19 columns]

In [25]:
idf.groupby([idf.index.get_level_values("Data").year, "Intervalo"])["PRECIPITAÇÃO TOTAL, HORÁRIO (mm)"].agg(["mean", "min", "max"])

                    mean  min  max
Data Intervalo
2003 Madrugada  0.000000  0.0  0.0
     Manhã      0.066667  0.0  0.4
     Noite      0.000000  0.0  0.0
     Tarde      0.000000  0.0  0.0
2013 Madrugada  0.000000  0.0  0.0
     Manhã      0.000000  0.0  0.0
     Noite      0.400000  0.0  1.6
     Tarde      0.000000  0.0  0.0
2023 Madrugada  0.000000  0.0  0.0
     Manhã      0.033333  0.0  0.2
     Noite      0.000000  0.0  0.0
     Tarde      0.000000  0.0  0.0

In [26]:
idf.groupby([idf.index.get_level_values("Data").year, "Intervalo"])["Temperatura"].agg(["mean", "min", "max"])

                                                Temperatura              \
               TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)
                                                       mean   min   max
Data Intervalo
2003 Madrugada                                    21.350000  20.8  21.8
     Manhã                                        20.450000  20.1  20.8
     Noite                                        22.950000  20.0  25.0
     Tarde                                        22.700000  21.4  23.4
2013 Madrugada                                    24.516667  22.4  26.8
     Manhã                                        21.950000  21.4  22.8
     Noite                                        23.600000  22.4  24.7
     Tarde                                        26.383333  23.5  28.5
2023 Madrugada                                    22.800000  22.1  23.6
     Manhã                                        21.733333  21.1  22.4
     Noite                                        26.466667  24.3  32.3
     Tarde                                        28.550000  25.9  30.4

                                                                 \
               TEMPERATURA DO PONTO DE ORVALHO (°C)
                                               mean   min   max
Data Intervalo
2003 Madrugada                            14.050000  13.0  14.8
     Manhã                                14.216667  13.2  15.6
     Noite                                13.800000  12.9  14.7
     Tarde                                14.183333  13.3  16.1
2013 Madrugada                            12.850000  11.8  14.1
     Manhã                                14.250000  13.0  15.3
     Noite                                17.350000  15.4  19.0
     Tarde                                14.883333  13.4  15.7
2023 Madrugada                            17.833333  17.6  18.2
     Manhã                                18.283333  17.9  18.5
     Noite                                15.133333  14.7  15.8
     Tarde                                17.100000  16.4  17.6

                                                                       \
               TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)
                                                     mean   min   max
Data Intervalo
2003 Madrugada                                  21.800000  21.1  22.4
     Manhã                                      21.166667  20.6  21.8
     Noite                                      23.816667  20.9  25.1
     Tarde                                      22.966667  21.6  23.7
2013 Madrugada                                  25.383333  23.1  27.1
     Manhã                                      22.333333  21.7  23.1
     Noite                                      25.016667  23.4  29.5
     Tarde                                      27.033333  23.5  28.9
2023 Madrugada                                  23.216667  22.8  23.8
     Manhã                                      22.016667  21.3  22.7
     Noite                                      28.100000  25.2  32.4
     Tarde                                      29.150000  26.1  31.4

                                                                       \
               TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C)
                                                     mean   min   max
Data Intervalo
2003 Madrugada                                  21.033333  20.8  21.6
     Manhã                                      20.300000  19.9  20.5
     Noite                                      22.516667  19.8  24.1
     Tarde                                      21.966667  20.2  23.0
2013 Madrugada                                  24.266667  22.4  26.3
     Manhã                                      21.533333  21.0  21.9
     Noite                                      22.950000  22.0  24.7
     Tarde                                      25.183333  22.8  27.0
2023 Madrugada                                  22.516667  21.6  23.6
     Manhã                                      21.433333  20.7  22.3
     Noite                                      25.916667  24.0  30.4
     Tarde                                      27.050000  22.4  29.3

                                                                             \
               TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C)
                                                           mean   min   max
Data Intervalo
2003 Madrugada                                        14.600000  13.7  15.1
     Manhã                                            14.516667  13.9  15.6
     Noite                                            14.216667  13.6  15.1
     Tarde                                            15.650000  14.2  16.9
2013 Madrugada                                        13.233333  12.0  14.3
     Manhã                                            14.466667  13.6  15.4
     Noite                                            18.333333  16.1  19.5
     Tarde                                            15.700000  14.9  16.4
2023 Madrugada                                        18.033333  17.7  18.2
     Manhã                                            18.383333  17.9  18.6
     Noite                                            15.800000  15.2  17.3
     Tarde                                            18.100000  17.2  19.0


               TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C)
                                                           mean   min   max
Data Intervalo
2003 Madrugada                                        13.566667  12.6  14.3
     Manhã                                            13.283333  12.0  14.2
     Noite                                            13.216667  12.4  14.4
     Tarde                                            13.416667  12.8  14.8
2013 Madrugada                                        12.200000  11.2  13.6
     Manhã                                            13.750000  12.8  14.9
     Noite                                            16.116667  14.1  17.7
     Tarde                                            14.100000  12.9  15.0
2023 Madrugada                                        17.700000  17.5  18.0
     Manhã                                            18.083333  17.7  18.4
     Noite                                            14.300000  13.4  15.1
     Tarde                                            16.583333  15.8  17.6